/* eslint-disable react-refresh/only-export-components */
import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const LANGUAGES = [
  { code: 'en', label: 'English' },
  { code: 'zh', label: '繁體中文' },
  { code: 'ja', label: '日本語' },
  { code: 'ko', label: '한국어' },
  { code: 'de', label: 'Deutsch' },
  { code: 'es', label: 'Español' },
  { code: 'fr', label: 'Français' },
  { code: 'th', label: 'ภาษาไทย' },
  { code: 'vi', label: 'Tiếng Việt' },
  { code: 'pt', label: 'Português' },
  { code: 'ru', label: 'Русский' }
];

const TRANSLATIONS = {
  en: {
    leader_slot_title: "Leader Slot",
    team_units_title: "Team Units",
    active_skill: "Active Skill",
    special_skill: "Special Skill",
    home: "Home",
    characters: "Characters",
    builder: "Team Builder",
    guides: "Guides",
    status: "Status",
    view_status: "View Status Page",
    leader_slot: "Leader Slot",
    team_units: "Team Units (Max 5)",
    active_passives: "Active Characters Skills",
    save_presets: "Save Presets Configuration",
    search_placeholder: "Search characters by name...",
    group: "Group",
    type: "Type",
    all: "All",
    active_presets_title: "Active Presets",
    leader_tag: "Leader",
    member_tag: "Member",
    guides_title: "Guides & Strategies",
    read_more: "Read More",
    database_title: "HoloDreams Database",
    database_desc: "View detailed profile information, character stats, and skill breakdowns for every Holo-talent.",
    skills_label: "Skills",
    builder_title: "Team Builder",
    builder_desc: "Click on any slot to assign members or the Leader. Match VTuber requirements to trigger Passive Skills.",
    presets_manager: "Presets Manager",
    presets_desc: "Switch presets or activate one as your primary deck (Active Party)",
    rename_preset: "Rename",
    copy_preset: "Copy",
    reset_preset: "Reset",
    make_active: "Set Active",
    smart_suggest: "Smart Suggest Team",
    empty_leader_placeholder: "Click to Select Leader",
    selecting_leader_placeholder: "Selecting Leader...",
    empty_slot_placeholder: "Slot {num}: Click to Select",
    selecting_slot_placeholder: "Selecting Slot {num}...",
    recommended_team_popup_title: "Smart Team Recommendation",
    apply_recommendation: "Apply Recommendation",
    cancel: "Cancel",
    select_char_modal_title: "Select Character to Add",
    filter_owned: "Owned Only",
    checking_status: "Checking System Status...",
    systems_operational: "All Systems Operational",
    systems_offline: "Systems Offline / Connection Error",
    systems_degraded: "Some Systems Degraded",
    admin_dash: "Admin Dashboard",
    guide_detail: "Guide Details",
    new_rpg_fan_game: "NEW RPG FAN-GAME",
    hero_title: "HOLOLIVE DREAMS",
    hero_subtitle: "Embark on a colorful dreamscape alongside your favorite VTubers. Explore detailed stats, build optimal teams, and customize your showcase profile.",
    view_characters: "View Characters",
    view_guides: "View Guides",
    view_all_articles: "View all articles",
    no_active_team: "No active team. Click to build your team!",
    by_author: "By {author}",
    read_time: "Read Time: {time}",
    leader_skill: "Leader Skill",
    passive_skill: "Passive Skill",
    inactive_skills_title: "Unsatisfied Skill Requirements",
    no_unsatisfied_skills: "No skills are unsatisfied. Your team is performing well!",
    no_active_skills_msg: "No active skills triggered for the current team.",
    add_members_msg: "Add members to the team to check for active Passive Skills.",
    editing_label: "Editing:",
    primary_active_party: "Primary Active Party",
    clear_slots: "Clear Slots",
    my_character_roster: "My Character Roster",
    select_all: "Select All",
    deselect_all: "Deselect All",
    roster_desc: "Configure which characters you own ({owned}/{total}). The recommendation engine will only suggest teams using checked characters."
  },
  vi: {
    leader_slot_title: "Trưởng nhóm",
    team_units_title: "Thành viên",
    active_skill: "Kỹ năng Chủ động",
    special_skill: "Kỹ năng Đặc biệt",
    home: "Trang chủ",
    characters: "Nhân vật",
    builder: "Đội hình",
    guides: "Hướng dẫn",
    status: "Trạng thái",
    view_status: "Xem trang trạng thái",
    leader_slot: "Vị trí Trưởng nhóm",
    team_units: "Thành viên đội (Tối đa 5)",
    active_passives: "Kỹ năng Đội hình",
    save_presets: "Lưu cấu hình Đội hình",
    search_placeholder: "Tìm nhân vật theo tên...",
    group: "Thế hệ",
    type: "Hệ",
    all: "Tất cả",
    active_presets_title: "Đội hình hoạt động",
    leader_tag: "Trưởng nhóm",
    member_tag: "Thành viên",
    guides_title: "Hướng dẫn & Chiến thuật",
    read_more: "Đọc thêm",
    database_title: "Thư viện HoloDreams",
    database_desc: "Xem thông tin chi tiết, chỉ số nhân vật và chi tiết kỹ năng của từng tài năng Hololive.",
    skills_label: "Kỹ năng",
    builder_title: "Xây dựng Đội hình",
    builder_desc: "Nhấn vào ô trống để chọn Trưởng nhóm hoặc Thành viên. Đạt điều kiện để kích hoạt Kỹ năng Bị động.",
    presets_manager: "Quản lý Đội hình mẫu",
    presets_desc: "Chuyển đổi giữa các đội hình mẫu hoặc đặt làm đội hình chính của bạn",
    rename_preset: "Đổi tên",
    copy_preset: "Sao chép",
    reset_preset: "Đặt lại",
    make_active: "Kích hoạt",
    smart_suggest: "Đội hình Đề xuất",
    empty_leader_placeholder: "Nhấp để chọn Trưởng nhóm",
    selecting_leader_placeholder: "Đang chọn Trưởng nhóm...",
    empty_slot_placeholder: "Slot {num}: Nhấp để chọn",
    selecting_slot_placeholder: "Đang chọn Slot {num}...",
    recommended_team_popup_title: "Đội hình Đề xuất Thông minh",
    apply_recommendation: "Áp dụng Đội hình",
    cancel: "Hủy",
    select_char_modal_title: "Chọn nhân vật thêm vào đội",
    filter_owned: "Chỉ nhân vật sở hữu",
    checking_status: "Đang kiểm tra trạng thái...",
    systems_operational: "Hệ thống ổn định",
    systems_offline: "Hệ thống ngoại tuyến / Lỗi kết nối",
    systems_degraded: "Một số hệ thống gặp lỗi",
    admin_dash: "Bảng quản trị",
    guide_detail: "Chi tiết bài viết",
    new_rpg_fan_game: "RPG FAN-GAME MỚI",
    hero_title: "HOLOLIVE DREAMS",
    hero_subtitle: "Khám phá thế giới mộng mơ đầy màu sắc cùng các VTubers yêu thích. Xem thông tin chi tiết, xây dựng đội hình và tùy biến hồ sơ trưng bày.",
    view_characters: "Xem nhân vật",
    view_guides: "Xem bài viết",
    view_all_articles: "Xem tất cả bài viết",
    no_active_team: "Chưa có đội hình chính. Click để xây dựng đội hình!",
    by_author: "Tác giả: {author}",
    read_time: "Thời gian đọc: {time}",
    leader_skill: "Kỹ năng Trưởng nhóm",
    passive_skill: "Kỹ năng Bị động",
    inactive_skills_title: "Kỹ năng chưa thỏa mãn yêu cầu",
    no_unsatisfied_skills: "Không có kỹ năng nào không được thỏa mãn yêu cầu, đội của bạn đang hoạt động tốt.",
    no_active_skills_msg: "Không có kỹ năng kích hoạt cho đội hình hiện tại.",
    add_members_msg: "Thêm thành viên vào đội hình để kiểm tra Kỹ năng Bị động.",
    editing_label: "Đang chỉnh sửa:",
    primary_active_party: "Đội hình hoạt động chính",
    clear_slots: "Làm trống đội",
    my_character_roster: "Danh sách nhân vật sở hữu",
    select_all: "Chọn tất cả",
    deselect_all: "Bỏ chọn tất cả",
    roster_desc: "Chọn nhân vật bạn sở hữu ({owned}/{total}). Bộ đề xuất thông minh sẽ chỉ lập đội bằng nhân vật được chọn."
  },
  ja: {
    leader_slot_title: "リーダー枠",
    team_units_title: "チームメンバー",
    active_skill: "アクティブスキル",
    special_skill: "スペシャルスキル",
    home: "ホーム",
    characters: "キャラクター",
    builder: "チーム編成",
    guides: "ガイド",
    status: "ステータス",
    view_status: "ステータスページ表示",
    leader_slot: "リーダー枠",
    team_units: "チームメンバー (最大5)",
    active_passives: "アクティブキャラクタースキル",
    save_presets: "編成を保存する",
    search_placeholder: "名前でキャラクターを検索...",
    group: "グループ",
    type: "タイプ",
    all: "すべて",
    active_presets_title: "現在の編成",
    leader_tag: "リーダー",
    member_tag: "メンバー",
    guides_title: "攻略ガイド＆戦略",
    read_more: "詳細を見る",
    database_title: "HoloDreams データベース",
    database_desc: "ホロライブメンバーのプロフィール、ステータス、スキル詳細を閲覧できます。",
    skills_label: "スキル",
    builder_title: "チームビルダー",
    builder_desc: "スロットをクリックしてリーダーやメンバーを配置します。条件を達成してパッシブを有効にしましょう。",
    presets_manager: "プリセット管理",
    presets_desc: "プリセットを切り替えるか、メインデッキとしてアクティブにします",
    rename_preset: "名前変更",
    copy_preset: "コピー",
    reset_preset: "リセット",
    make_active: "アクティブ化",
    smart_suggest: "スマートおすすめ編成",
    empty_leader_placeholder: "クリックしてリーダーを選択",
    selecting_leader_placeholder: "リーダー選択中...",
    empty_slot_placeholder: "スロット {num}: クリックして選択",
    selecting_slot_placeholder: "スロット {num} 選択中...",
    recommended_team_popup_title: "スマートおすすめ編成提案",
    apply_recommendation: "提案を適用",
    cancel: "キャンセル",
    select_char_modal_title: "追加するメンバーを選択",
    filter_owned: "所持済みのみ",
    checking_status: "状態チェック中...",
    systems_operational: "全システム正常稼働中",
    systems_offline: "接続エラー / オフライン",
    systems_degraded: "一部システム障害発生中",
    admin_dash: "管理ダッシュボード",
    guide_detail: "ガイド詳細",
    new_rpg_fan_game: "新作RPGファンゲーム",
    hero_title: "HOLOLIVE DREAMS",
    hero_subtitle: "お気に入りのVTuberたちとカラフルな夢の世界へ旅立とう。詳細なステータスを確認し、最強のチームを編成しよう。",
    view_characters: "キャラクター一覧",
    view_guides: "ガイド一覧",
    view_all_articles: "すべての記事を見る",
    no_active_team: "編成されていません。クリックして編成を始めましょう！",
    by_author: "作成者: {author}",
    read_time: "所要時間: {time}",
    leader_skill: "リーダースキル",
    passive_skill: "パッシブスキル",
    inactive_skills_title: "未発動のスキル条件",
    no_unsatisfied_skills: "条件を満たしていないスキルはありません。チームは最高の状態です！",
    no_active_skills_msg: "現在のチームで発動しているスキルはありません。",
    add_members_msg: "チームメンバーを追加してスキル発動状況を確認しましょう。",
    editing_label: "編集名:",
    primary_active_party: "主要のアクティブパーティ",
    clear_slots: "スロットをクリア",
    my_character_roster: "所持キャラクター一覧",
    select_all: "すべて選択",
    deselect_all: "選択解除",
    roster_desc: "所持しているキャラクターを設定します ({owned}/{total})。おすすめ編成ではチェックしたメンバーのみを使用します。"
  },
  zh: {
    leader_slot_title: "隊長欄位",
    team_units_title: "隊員欄位",
    active_skill: "主動技能",
    special_skill: "特殊技能",
    home: "首頁",
    characters: "角色圖鑑",
    builder: "隊伍編成",
    guides: "攻略指南",
    status: "系統狀態",
    view_status: "查看狀態頁面",
    leader_slot: "隊長欄位",
    team_units: "隊員名單 (最多5名)",
    active_passives: "出戰角色技能",
    save_presets: "儲存隊伍配置",
    search_placeholder: "輸入名字搜尋角色...",
    group: "期數 / 組合",
    type: "屬性",
    all: "全部",
    active_presets_title: "當前配置隊伍",
    leader_tag: "隊長",
    member_tag: "隊員",
    guides_title: "指南與戰術",
    read_more: "閱讀更多",
    database_title: "HoloDreams 數據庫",
    database_desc: "查看每位 Hololive 成員的詳細資料、屬性數值及技能介紹。",
    skills_label: "技能列表",
    builder_title: "隊伍編成器",
    builder_desc: "點選欄位來指派隊長或隊員。符合特定成員要求以觸發被動技能。",
    presets_manager: "隊伍預設管理器",
    presets_desc: "切換隊伍預設或將其設為主要出戰隊伍",
    rename_preset: "重新命名",
    copy_preset: "複製預設",
    reset_preset: "重設欄位",
    make_active: "設為出戰",
    smart_suggest: "智能推薦陣容",
    empty_leader_placeholder: "點擊選擇隊長",
    selecting_leader_placeholder: "正在選擇隊長...",
    empty_slot_placeholder: "位置 {num}: 點擊選擇",
    selecting_slot_placeholder: "正在選擇位置 {num}...",
    recommended_team_popup_title: "智能陣容推薦",
    apply_recommendation: "套用推薦陣容",
    cancel: "取消",
    select_char_modal_title: "選擇要加入的角色",
    filter_owned: "僅顯示已擁有",
    checking_status: "正在檢查系統狀態...",
    systems_operational: "所有系統正常運作",
    systems_offline: "系統斷線 / 連線錯誤",
    systems_degraded: "部分系統運作受阻",
    admin_dash: "管理後台",
    guide_detail: "攻略詳情",
    new_rpg_fan_game: "全新同人RPG遊戲",
    hero_title: "HOLOLIVE DREAMS",
    hero_subtitle: "與你最愛的VTuber一同踏入繽紛的夢境。查看詳細數值，打造完美陣容，定製個人名片。",
    view_characters: "查看角色",
    view_guides: "查看攻略",
    view_all_articles: "查看所有文章",
    no_active_team: "尚未配置出戰隊伍。點擊開始組建！",
    by_author: "作者: {author}",
    read_time: "閱讀時間: {time}",
    leader_skill: "隊長技能",
    passive_skill: "被動技能",
    inactive_skills_title: "未滿足的技能要求",
    no_unsatisfied_skills: "所有技能要求均已滿足。您的隊伍運作良好！",
    no_active_skills_msg: "當前隊伍沒有觸發任何技能。",
    add_members_msg: "新增隊員以檢查被動技能觸發狀況。",
    editing_label: "正在編輯:",
    primary_active_party: "主要出戰隊伍",
    clear_slots: "清除欄位",
    my_character_roster: "擁有角色名冊",
    select_all: "選擇全部",
    deselect_all: "取消全選",
    roster_desc: "配置您所擁有的角色 ({owned}/{total})。智能陣容推薦將僅使用勾選的角色進行組合。"
  },
  ko: {
    leader_slot_title: "리더 슬롯",
    team_units_title: "팀 멤버",
    active_skill: "액티브 스킬",
    special_skill: "스페셜 스킬",
    home: "홈",
    characters: "캐릭터 도감",
    builder: "팀 편성",
    guides: "공략 가이드",
    status: "시스템 상태",
    view_status: "상태 페이지 보기",
    leader_slot: "리더 슬롯",
    team_units: "팀 멤버 (최대 5명)",
    active_passives: "액티브 캐릭터 스킬",
    save_presets: "팀 편성 저장",
    search_placeholder: "이름으로 캐릭터 검색...",
    group: "기수 / 그룹",
    type: "타입",
    all: "전체",
    active_presets_title: "현재 저장된 편성",
    leader_tag: "리더",
    member_tag: "멤버",
    guides_title: "가이드 및 전략",
    read_more: "자세히 보기",
    database_title: "HoloDreams 데이터베이스",
    database_desc: "모든 홀로라이브 멤버들의 상세 스탯 및 스킬을 확인하세요.",
    skills_label: "스킬 목록",
    builder_title: "팀 빌더",
    builder_desc: "슬롯을 클릭하여 리더 또는 팀원을 배치합니다. 조건에 맞게 배치하면 패시브 스킬이 발동합니다.",
    presets_manager: "프리셋 매니저",
    presets_desc: "팀 편성을 전환하거나 기본 덱(출전 파티)으로 활성화합니다",
    rename_preset: "이름 변경",
    copy_preset: "복사",
    reset_preset: "초기화",
    make_active: "출전 설정",
    smart_suggest: "스마트 추천 편성",
    empty_leader_placeholder: "클릭하여 리더 선택",
    selecting_leader_placeholder: "리더 선택 중...",
    empty_slot_placeholder: "슬롯 {num}: 클릭하여 선택",
    selecting_slot_placeholder: "슬롯 {num} 선택 중...",
    recommended_team_popup_title: "스마트 팀 추천",
    apply_recommendation: "추천 편성 적용",
    cancel: "취소",
    select_char_modal_title: "추가할 캐릭터 선택",
    filter_owned: "보유 캐릭터만",
    checking_status: "시스템 상태 확인 중...",
    systems_operational: "모든 시스템 정상 작동 중",
    systems_offline: "오프라인 / 연결 오류",
    systems_degraded: "일부 시스템 장애 발생",
    admin_dash: "관리자 대시보드",
    guide_detail: "가이드 상세",
    new_rpg_fan_game: "새로운 RPG 팬 게임",
    hero_title: "HOLOLIVE DREAMS",
    hero_subtitle: "가장 좋아하는 VTuber들과 함께 알록달록한 꿈의 세계로 떠나보세요. 상세 스탯을 탐색하고 팀을 최적화하세요.",
    view_characters: "캐릭터 보기",
    view_guides: "가이드 보기",
    view_all_articles: "모든 가이드 보기",
    no_active_team: "활성화된 팀이 없습니다. 클릭하여 나만의 팀을 만들어보세요!",
    by_author: "작성자: {author}",
    read_time: "소요 시간: {time}",
    leader_skill: "리더 스킬",
    passive_skill: "패시브 스킬",
    inactive_skills_title: "미발동 스킬 조건",
    no_unsatisfied_skills: "불만족된 스킬 조건이 없습니다. 팀이 완벽하게 가동 중입니다!",
    no_active_skills_msg: "현재 편성된 팀에 활성화된 스킬이 없습니다.",
    add_members_msg: "팀원을 배치하여 패시브 스킬 조건을 확인해보세요.",
    editing_label: "편집 중:",
    primary_active_party: "기본 출전 파티",
    clear_slots: "슬롯 초기화",
    my_character_roster: "보유 캐릭터 목록",
    select_all: "전체 선택",
    deselect_all: "전체 해제",
    roster_desc: "보유한 캐릭터를 설정합니다 ({owned}/{total}). 스마트 추천 엔진은 체크된 캐릭터만 사용하여 팀을 제안합니다."
  },
  de: {
    leader_slot_title: "Leader-Slot",
    team_units_title: "Team-Mitglieder",
    active_skill: "Aktive Fähigkeit",
    special_skill: "Spezialfähigkeit",
    home: "Startseite",
    characters: "Charaktere",
    builder: "Teambildung",
    guides: "Guides",
    status: "Status",
    view_status: "Statusseite anzeigen",
    leader_slot: "Anführer-Slot",
    team_units: "Teameinheiten (Max 5)",
    active_passives: "Aktive Charakterfähigkeiten",
    save_presets: "Preset-Konfiguration speichern",
    search_placeholder: "Charaktere nach Name suchen...",
    group: "Gruppe",
    type: "Typ",
    all: "Alle",
    active_presets_title: "Aktive Presets",
    leader_tag: "Anführer",
    member_tag: "Mitglied",
    guides_title: "Guides & Strategien",
    read_more: "Mehr lesen",
    database_title: "HoloDreams-Datenbank",
    database_desc: "Detaillierte Profilinformationen, Charakterwerte und Skill-Details für jedes Holo-Talent ansehen.",
    skills_label: "Fähigkeiten",
    builder_title: "Teambuilder",
    builder_desc: "Klicke auf einen Slot, um Mitglieder oder den Anführer zuzuweisen. Erfülle Bedingungen für passive Skills.",
    presets_manager: "Preset-Manager",
    presets_desc: "Wechsle Presets oder aktiviere eines als Hauptdeck (Aktive Party)",
    rename_preset: "Umbenennen",
    copy_preset: "Kopieren",
    reset_preset: "Zurücksetzen",
    make_active: "Aktivieren",
    smart_suggest: "Teamebene vorschlagen",
    empty_leader_placeholder: "Klicken, um Anführer zu wählen",
    selecting_leader_placeholder: "Wähle Anführer...",
    empty_slot_placeholder: "Slot {num}: Klicken zum Wählen",
    selecting_slot_placeholder: "Wähle Slot {num}...",
    recommended_team_popup_title: "Smarte Team-Empfehlung",
    apply_recommendation: "Empfehlung anwenden",
    cancel: "Abbrechen",
    select_char_modal_title: "Charakter zum Hinzufügen wählen",
    filter_owned: "Nur im Besitz",
    checking_status: "Prüfe Systemstatus...",
    systems_operational: "Alle Systeme betriebsbereit",
    systems_offline: "Systeme offline / Verbindungsfehler",
    systems_degraded: "Einige Systeme beeinträchtigt",
    admin_dash: "Admin-Dashboard",
    guide_detail: "Guide-Details",
    new_rpg_fan_game: "NEUES RPG FAN-SPIEL",
    hero_title: "HOLOLIVE DREAMS",
    hero_subtitle: "Begib dich auf eine bunte Traumlandschaft an der Seite deiner Lieblings-VTuber. Erkunde Statistiken und erstelle Teams.",
    view_characters: "Charaktere ansehen",
    view_guides: "Guides ansehen",
    view_all_articles: "Alle Artikel anzeigen",
    no_active_team: "Kein aktives Team. Klicke, um ein Team zu erstellen!",
    by_author: "Von {author}",
    read_time: "Lesezeit: {time}",
    leader_skill: "Anführer-Skill",
    passive_skill: "Passiver Skill",
    inactive_skills_title: "Unerfüllte Skill-Bedingungen",
    no_unsatisfied_skills: "Alle Skill-Bedingungen sind erfüllt. Ihr Team läuft perfekt!",
    no_active_skills_msg: "Keine aktiven Skills für das aktuelle Team.",
    add_members_msg: "Füge Mitglieder hinzu, um aktive passive Fähigkeiten zu prüfen.",
    editing_label: "Bearbeiten:",
    primary_active_party: "Haupt-Aktiv-Gruppe",
    clear_slots: "Slots leeren",
    my_character_roster: "Mein Roster",
    select_all: "Alle auswählen",
    deselect_all: "Auswahl aufheben",
    roster_desc: "Besitz ({owned}/{total}). Empfehlung schlägt nur Teams mit markierten Charakteren vor."
  },
  es: {
    leader_slot_title: "Casilla del Líder",
    team_units_title: "Miembros del Equipo",
    active_skill: "Habilidad Activa",
    special_skill: "Habilidad Especial",
    home: "Inicio",
    characters: "Personajes",
    builder: "Creador de Equipos",
    guides: "Guías",
    status: "Estado",
    view_status: "Ver página de estado",
    leader_slot: "Ranura de Líder",
    team_units: "Unidades de Equipo (Máx. 5)",
    active_passives: "Habilidades de Personajes Activos",
    save_presets: "Guardar Configuración",
    search_placeholder: "Buscar personajes...",
    group: "Grupo",
    type: "Tipo",
    all: "Todos",
    active_presets_title: "Ajustes Activos",
    leader_tag: "Líder",
    member_tag: "Miembro",
    guides_title: "Guías & Estrategias",
    read_more: "Leer más",
    database_title: "Base de Datos",
    database_desc: "Ver perfiles detallados, estadísticas y habilidades de cada talento de Hololive.",
    skills_label: "Habilidades",
    builder_title: "Creador de Equipos",
    builder_desc: "Haz clic en una ranura para asignar miembros. Cumple requisitos para activar habilidades pasivas.",
    presets_manager: "Gestor de Ajustes",
    presets_desc: "Cambia de ajustes o activa uno como baraja principal",
    rename_preset: "Renombrar",
    copy_preset: "Copiar",
    reset_preset: "Reiniciar",
    make_active: "Activar",
    smart_suggest: "Sugerencia Inteligente",
    empty_leader_placeholder: "Clic para seleccionar Líder",
    selecting_leader_placeholder: "Seleccionando Líder...",
    empty_slot_placeholder: "Ranura {num}: Clic para seleccionar",
    selecting_slot_placeholder: "Seleccionando Ranura {num}...",
    recommended_team_popup_title: "Recomendación de Equipo",
    apply_recommendation: "Aplicar Recomendación",
    cancel: "Cancelar",
    select_char_modal_title: "Seleccionar personaje para añadir",
    filter_owned: "Solo en posesión",
    checking_status: "Verificando estado del sistema...",
    systems_operational: "Todos los sistemas operativos",
    systems_offline: "Sistemas sin conexión / Error de conexión",
    systems_degraded: "Algunos sistemas degradados",
    admin_dash: "Panel de Admin",
    guide_detail: "Detalles de Guía",
    new_rpg_fan_game: "NUEVO FAN-GAME RPG",
    hero_title: "HOLOLIVE DREAMS",
    hero_subtitle: "Embárcate en un colorido paisaje de ensueño con tus VTubers favoritos. Explora estadísticas y crea equipos.",
    view_characters: "Ver Personajes",
    view_guides: "Ver Guías",
    view_all_articles: "Ver todos los artículos",
    no_active_team: "Sin equipo activo. ¡Clic para crear tu equipo!",
    by_author: "Por {author}",
    read_time: "Lectura: {time}",
    leader_skill: "Habilidad de Líder",
    passive_skill: "Habilidad Pasiva",
    inactive_skills_title: "Requisitos de Habilidad no Cumplidos",
    no_unsatisfied_skills: "Todos los requisitos de habilidad están cumplidos. ¡Tu equipo funciona perfectamente!",
    no_active_skills_msg: "Ninguna habilidad activa activada para el equipo actual.",
    add_members_msg: "Añade miembros al equipo para verificar las habilidades pasivas.",
    editing_label: "Editando:",
    primary_active_party: "Grupo Activo Principal",
    clear_slots: "Limpiar ranuras",
    my_character_roster: "Mi Lista",
    select_all: "Seleccionar todo",
    deselect_all: "Deseleccionar todo",
    roster_desc: "Posesión ({owned}/{total}). Recomendación solo sugerirá marcados."
  },
  fr: {
    leader_slot_title: "Emplacement du Leader",
    team_units_title: "Membres de l'Équipe",
    active_skill: "Compétence Active",
    special_skill: "Compétence Spéciale",
    home: "Accueil",
    characters: "Personnages",
    builder: "Composition",
    guides: "Guides",
    status: "Statut",
    view_status: "Voir la page de statut",
    leader_slot: "Emplacement Leader",
    team_units: "Membres de l'équipe (Max 5)",
    active_passives: "Compétences de Personnages Actifs",
    save_presets: "Sauvegarder",
    search_placeholder: "Rechercher...",
    group: "Groupe",
    type: "Type",
    all: "Tous",
    active_presets_title: "Compositions actives",
    leader_tag: "Leader",
    member_tag: "Membre",
    guides_title: "Guides & Stratégies",
    read_more: "Lire la suite",
    database_title: "Base de données",
    database_desc: "Fiches détaillées, statistiques et compétences pour chaque talent Hololive.",
    skills_label: "Compétences",
    builder_title: "Création d'équipe",
    builder_desc: "Assignez le Leader ou des membres. Remplissez les conditions pour activer les passifs.",
    presets_manager: "Gestionnaire de presets",
    presets_desc: "Changez de preset ou activez-en un comme équipe active",
    rename_preset: "Renommer",
    copy_preset: "Copier",
    reset_preset: "Réinitialiser",
    make_active: "Activer",
    smart_suggest: "Suggestion Intelligente",
    empty_leader_placeholder: "Cliquer pour choisir un Leader",
    selecting_leader_placeholder: "Sélection du Leader...",
    empty_slot_placeholder: "Slot {num}: Cliquer pour choisir",
    selecting_slot_placeholder: "Sélection du Slot {num}...",
    recommended_team_popup_title: "Suggestion d'Équipe",
    apply_recommendation: "Appliquer la suggestion",
    cancel: "Annuler",
    select_char_modal_title: "Sélectionner un personnage",
    filter_owned: "Possédé uniquement",
    checking_status: "Vérification du statut du système...",
    systems_operational: "Tous les systèmes sont opérationnels",
    systems_offline: "Systèmes hors ligne",
    systems_degraded: "Certains systèmes sont dégradés",
    admin_dash: "Tableau de bord",
    guide_detail: "Détails du Guide",
    new_rpg_fan_game: "NOUVEAU RPG FAN-GAME",
    hero_title: "HOLOLIVE DREAMS",
    hero_subtitle: "Partez pour un monde onirique coloré aux côtés de vos VTubers préférés. Explorez et créez l'équipe parfaite.",
    view_characters: "Voir les Personnages",
    view_guides: "Voir les Guides",
    view_all_articles: "Voir tous les articles",
    no_active_team: "Aucune équipe active. Cliquez pour en créer une !",
    by_author: "Par {author}",
    read_time: "Lecture: {time}",
    leader_skill: "Compétence de Chef",
    passive_skill: "Compétence Passive",
    inactive_skills_title: "Exigences de Compétence Non Remplies",
    no_unsatisfied_skills: "Toutes les conditions de compétence sont remplies. Votre équipe fonctionne parfaitement !",
    no_active_skills_msg: "Aucune compétence active déclenchée pour l'équipe actuelle.",
    add_members_msg: "Ajoutez des membres à l'équipe pour vérifier les passifs.",
    editing_label: "Édition :",
    primary_active_party: "Équipe Active Principale",
    clear_slots: "Vider les emplacements",
    my_character_roster: "Mon Catalogue",
    select_all: "Tout Sélectionner",
    deselect_all: "Tout Désélectionner",
    roster_desc: "Possédé ({owned}/{total}). La suggestion n'inclut que les cochés."
  },
  th: {
    leader_slot_title: "ช่องหัวหน้าทีม",
    team_units_title: "สมาชิกในทีม",
    active_skill: "สกิลใช้งาน",
    special_skill: "สกิลพิเศษ",
    home: "หน้าแรก",
    characters: "ตัวละคร",
    builder: "จัดทีม",
    guides: "คู่มือ",
    status: "สถานะระบบ",
    view_status: "ดูหน้าสถานะ",
    leader_slot: "ช่องหัวหน้าทีม",
    team_units: "สมาชิกทีม (สูงสุด 5)",
    active_passives: "สกิลของตัวละครที่เปิดใช้งาน",
    save_presets: "บันทึกทีม",
    search_placeholder: "ค้นหา...",
    group: "รุ่น / กลุ่ม",
    type: "ประเภท",
    all: "ทั้งหมด",
    active_presets_title: "ทีมที่ใช้งานอยู่",
    leader_tag: "หัวหน้า",
    member_tag: "สมาชิก",
    guides_title: "คู่มือและกลยุทธ์",
    read_more: "อ่านเพิ่มเติม",
    database_title: "ฐานข้อมูล",
    database_desc: "ประวัติอย่างละเอียด ค่าสถานะตัวละคร และรายละเอียดสกิลของสมาชิก Hololive ทุกคน",
    skills_label: "สกิล",
    builder_title: "จัดทีม",
    builder_desc: "คลิกจัดวางหัวหน้าหรือสมาชิกทีม ทำตามเงื่อนไขเพื่อเปิดสกิลติดตัว",
    presets_manager: "จัดการทีมพรีเซ็ต",
    presets_desc: "สลับพรีเซ็ตทีมหรือตั้งค่าเป็นทีมหลัก",
    rename_preset: "เปลี่ยนชื่อ",
    copy_preset: "คัดลอก",
    reset_preset: "รีเซ็ต",
    make_active: "ตั้งใช้งาน",
    smart_suggest: "แนะนำจัดทีมอัจฉริยะ",
    empty_leader_placeholder: "คลิกเพื่อเลือกหัวหน้าทีม",
    selecting_leader_placeholder: "กำลังเลือกหัวหน้า...",
    empty_slot_placeholder: "ช่อง {num}: คลิกเพื่อเลือก",
    selecting_slot_placeholder: "กำลังเลือกช่อง {num}...",
    recommended_team_popup_title: "แนะนำจัดทีม",
    apply_recommendation: "ใช้ทีมแนะนำ",
    cancel: "ยกเลิก",
    select_char_modal_title: "เลือกตัวละคร",
    filter_owned: "เฉพาะที่มีอยู่",
    checking_status: "กำลังตรวจสอบสถานะระบบ...",
    systems_operational: "ทุกระบบทำงานปกติ",
    systems_offline: "ระบบออฟไลน์",
    systems_degraded: "บางระบบทำงานได้ไม่ดี",
    admin_dash: "ระบบหลังบ้าน",
    guide_detail: "รายละเอียดคู่มือ",
    new_rpg_fan_game: "เกมแฟนเมด RPG ใหม่",
    hero_title: "HOLOLIVE DREAMS",
    hero_subtitle: "เริ่มต้นการเดินทางในโลกแห่งความฝันไปกับ VTuber ที่คุณชื่นชอบ จัดทีมและตื่นตาตื่นใจไปกับพลังของพวกเธอ",
    view_characters: "ดูตัวละคร",
    view_guides: "ดูคู่มือ",
    view_all_articles: "ดูบทความทั้งหมด",
    no_active_team: "ไม่มีทีมหลักที่ใช้งาน คลิกเพื่อสร้างทีมหลักของคุณ!",
    by_author: "โดย {author}",
    read_time: "อ่าน: {time}",
    leader_skill: "สกิลหัวหน้าทีม",
    passive_skill: "สกิลติดตัว",
    inactive_skills_title: "สกิลที่ยังไม่เปิดใช้งาน",
    no_unsatisfied_skills: "เงื่อนไขสกิลทั้งหมดได้รับการเปิดใช้งานแล้ว ทีมของคุณพร้อมลุย!",
    no_active_skills_msg: "ไม่มีสกิลที่ทำงานอยู่ในขณะนี้",
    add_members_msg: "เพิ่มสมาชิกทีมเพื่อตรวจสอบการทำงานของสกิลติดตัว",
    editing_label: "กำลังแก้ไข:",
    primary_active_party: "ทีมหลักที่ใช้งาน",
    clear_slots: "ล้างช่องข้อมูล",
    my_character_roster: "รายชื่อของฉัน",
    select_all: "เลือกทั้งหมด",
    deselect_all: "ยกเลิกการเลือกทั้งหมด",
    roster_desc: "มี ({owned}/{total}) ระบบจะแนะนำเฉพาะตัวละครที่เลือก"
  },
  pt: {
    leader_slot_title: "Espaço do Líder",
    team_units_title: "Membros da Equipe",
    active_skill: "Habilidade Ativa",
    special_skill: "Habilidade Especial",
    home: "Início",
    characters: "Personagens",
    builder: "Criador de Equipa",
    guides: "Guias",
    status: "Estado",
    view_status: "Ver página de estado",
    leader_slot: "Slot de Líder",
    team_units: "Unidades de Equipa (Máx 5)",
    active_passives: "Habilidades de Personagens Ativos",
    save_presets: "Salvar Presets",
    search_placeholder: "Procurar...",
    group: "Grupo",
    type: "Tipo",
    all: "Todos",
    active_presets_title: "Equipas Ativas",
    leader_tag: "Líder",
    member_tag: "Membro",
    guides_title: "Guias & Estratégias",
    read_more: "Ler mais",
    database_title: "Base de Dados",
    database_desc: "Ver perfis detalhados, estatísticas e habilidades para cada talento Hololive.",
    skills_label: "Habilidades",
    builder_title: "Criador de Equipa",
    builder_desc: "Clique num slot para atribuir membros. Complete requisitos para ativar as passivas.",
    presets_manager: "Gestor de Equipas",
    presets_desc: "Alterne entre equipas ou ative uma como equipa principal",
    rename_preset: "Renombrar",
    copy_preset: "Copiar",
    reset_preset: "Repor",
    make_active: "Ativar",
    smart_suggest: "Sugestão Inteligente",
    empty_leader_placeholder: "Clique para selecionar Líder",
    selecting_leader_placeholder: "A selecionar Líder...",
    empty_slot_placeholder: "Slot {num}: Clique para selecionar",
    selecting_slot_placeholder: "A selecionar Slot {num}...",
    recommended_team_popup_title: "Recomendação de Equipa",
    apply_recommendation: "Aplicar Recomendação",
    cancel: "Cancelar",
    select_char_modal_title: "Selecionar personagem",
    filter_owned: "Apenas em posse",
    checking_status: "Verificando status...",
    systems_operational: "Todos os sistemas operacionais",
    systems_offline: "Sistemas offline",
    systems_degraded: "Alguns sistemas degradados",
    admin_dash: "Painel Admin",
    guide_detail: "Detalhes do Guia",
    new_rpg_fan_game: "NOVO JOGO FAN-GAME RPG",
    hero_title: "HOLOLIVE DREAMS",
    hero_subtitle: "Embarque num colorido mundo onírico com as suas VTubers favoritas. Explore status e monte equipas.",
    view_characters: "Ver Personagens",
    view_guides: "Ver Guias",
    view_all_articles: "Ver todos os artigos",
    no_active_team: "Sem equipa ativa. Clique para montar uma equipa!",
    by_author: "Por {author}",
    read_time: "Leitura: {time}",
    leader_skill: "Habilidade de Líder",
    passive_skill: "Habilidade Passiva",
    inactive_skills_title: "Requisitos de Habilidade não Cumpridos",
    no_unsatisfied_skills: "Todos os requisitos de habilidade foram cumpridos. A sua equipa está a funcionar perfeitamente!",
    no_active_skills_msg: "Nenhuma habilidade ativa ativada para o grupo atual.",
    add_members_msg: "Adicione membros ao grupo para verificar as passivas.",
    editing_label: "Editando:",
    primary_active_party: "Equipa Ativa Principal",
    clear_slots: "Limpar Slots",
    my_character_roster: "Meu Catálogo",
    select_all: "Selecionar Todos",
    deselect_all: "Desmarcar Todos",
    roster_desc: "Posse ({owned}/{total}). Sugestão só propõe assinalados."
  },
  ru: {
    leader_slot_title: "Слот лидера",
    team_units_title: "Члены команды",
    active_skill: "Активный навык",
    special_skill: "Специальный навык",
    home: "Главная",
    characters: "Персонажи",
    builder: "Отряд",
    guides: "Руководства",
    status: "Статус",
    view_status: "Посмотреть страницу статуса",
    leader_slot: "Слот Лидера",
    team_units: "Члены отряда (Макс. 5)",
    active_passives: "Активные навыки персонажей",
    save_presets: "Сохранить отряды",
    search_placeholder: "Поиск...",
    group: "Поколение",
    type: "Тип",
    all: "Все",
    active_presets_title: "Сохраненные отряды",
    leader_tag: "Лидер",
    member_tag: "Участник",
    guides_title: "Руководства и тактики",
    read_more: "Читать далее",
    database_title: "База данных",
    database_desc: "Подробные профили, характеристики и навыки каждого таланта Hololive.",
    skills_label: "Навыки",
    builder_title: "Редактор отряда",
    builder_desc: "Нажмите на слот, чтобы назначить Лидера или членов отряда.",
    presets_manager: "Шаблоны отрядов",
    presets_desc: "Переключайте шаблоны или активируйте один как основной отряд",
    rename_preset: "Переименовать",
    copy_preset: "Копировать",
    reset_preset: "Сбросить",
    make_active: "Активировать",
    smart_suggest: "Умный подбор отряда",
    empty_leader_placeholder: "Нажмите для выбора Лидера",
    selecting_leader_placeholder: "Выбор Лидера...",
    empty_slot_placeholder: "Слот {num}: Нажмите для выбора",
    selecting_slot_placeholder: "Выбор слота {num}...",
    recommended_team_popup_title: "Рекомендация отряда",
    apply_recommendation: "Применить сборку",
    cancel: "Отмена",
    select_char_modal_title: "Выберите персонажа",
    filter_owned: "Только имеющиеся",
    checking_status: "Проверка статуса систем...",
    systems_operational: "Все системы работают нормально",
    systems_offline: "Системы оффлайн",
    systems_degraded: "Некоторые системы перегружены",
    admin_dash: "Панель администратора",
    guide_detail: "Детали руководства",
    new_rpg_fan_game: "НОВАЯ ФАН-ИГРА RPG",
    hero_title: "HOLOLIVE DREAMS",
    hero_subtitle: "Отправляйтесь в красочный сон с любимыми VTuber. Исследуйте их силу и собирайте идеальные отряды.",
    view_characters: "Посмотреть персонажей",
    view_guides: "Посмотреть руководства",
    view_all_articles: "Все статьи",
    no_active_team: "Нет активного отряда. Нажмите, чтобы собрать команду!",
    by_author: "Автор: {author}",
    read_time: "Время: {time}",
    leader_skill: "Навык лидера",
    passive_skill: "Пассивный навык",
    inactive_skills_title: "Неактивные требования навыков",
    no_unsatisfied_skills: "Все требования навыков выполнены. Ваш отряд работает отлично!",
    no_active_skills_msg: "Нет активных навыков для текущего отряда.",
    add_members_msg: "Добавьте участников в отряд для проверки пассивных навыков.",
    editing_label: "Редактирование:",
    primary_active_party: "Основной отряд",
    clear_slots: "Очистить слоты",
    my_character_roster: "Моя коллекция",
    select_all: "Выбрать все",
    deselect_all: "Снять выбор",
    roster_desc: "Имеется ({owned}/{total}). Автоподбор использует только отмеченных персонажей."
  }
};

export function LanguageProvider({ children }) {
  const [currentLang, setLangState] = useState(() => {
    return localStorage.getItem('theme_language') || 'en';
  });

  const setLang = (code) => {
    if (TRANSLATIONS[code]) {
      setLangState(code);
      localStorage.setItem('theme_language', code);
    }
  };

  const t = (key, params = {}) => {
    const langDict = TRANSLATIONS[currentLang] || TRANSLATIONS['en'];
    let text = langDict[key] || TRANSLATIONS['en'][key] || key;
    
    // Replace parameters if any, e.g. {num} or {owned} or {total}
    Object.keys(params).forEach(p => {
      text = text.replace(`{${p}}`, params[p]);
    });
    return text;
  };

  return (
    <LanguageContext.Provider value={{ currentLang, setLang, t, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
