/* eslint-disable react-refresh/only-export-components */
import React, { createContext, useContext, useState, useEffect } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';

const LanguageContext = createContext();

export const LANGUAGES = [
  { code: 'en', label: 'English' },
  { code: 'zh', label: '繁體中文' },
  { code: 'ja', label: '日本語' },
  { code: 'ko', label: '한국어' },
  { code: 'de', label: 'Deutsch' },
  { code: 'es', label: 'Español' },
  { code: 'fr', label: 'Français' },
  { code: 'th', label: 'ภาษาไทย' },
  { code: 'vi', label: 'Tiếng Việt' },
  { code: 'pt', label: 'Português' },
  { code: 'ru', label: 'Русский' }
];

const TRANSLATIONS = {
  en: {
    leader_slot_title: "Leader Slot",
    team_units_title: "Team Units",
    active_skill: "Active Skill",
    special_skill: "Special Skill",
    home: "Home",
    characters: "Characters",
    builder: "Team Builder",
    guides: "Guides",
    status: "Status",
    view_status: "View Status Page",
    leader_slot: "Leader Slot",
    team_units: "Team Units (Max 5)",
    active_passives: "Active Characters Skills",
    save_presets: "Save Presets Configuration",
    search_placeholder: "Search characters by name...",
    group: "Group",
    type: "Type",
    all: "All",
    active_presets_title: "Active Presets",
    leader_tag: "Leader",
    member_tag: "Member",
    guides_title: "Guides & Strategies",
    guides_page_title: "Game Guides & Blog",
    guides_page_subtitle: "Learn strategies, character insights, and guide builds to optimize your Hololive Dreams progression.",
    read_more: "Read More",
    database_title: "HoloDreams Database",
    database_desc: "View detailed profile information, character stats, and skill breakdowns for every Holo-talent.",
    skills_label: "Skills",
    builder_title: "Team Builder",
    builder_desc: "Click on any slot to assign members or the Leader. Match VTuber requirements to trigger Passive Skills.",
    presets_manager: "Presets Manager",
    presets_desc: "Switch presets or activate one as your primary deck (Active Party)",
    rename_preset: "Rename",
    copy_preset: "Copy",
    reset_preset: "Reset",
    make_active: "Set Active",
    smart_suggest: "Smart Suggest Team",
    empty_leader_placeholder: "Click to Select Leader",
    selecting_leader_placeholder: "Selecting Leader...",
    empty_slot_placeholder: "Slot {num}: Click to Select",
    selecting_slot_placeholder: "Selecting Slot {num}...",
    recommended_team_popup_title: "Smart Team Recommendation",
    apply_recommendation: "Apply Recommendation",
    cancel: "Cancel",
    select_char_modal_title: "Select Character to Add",
    filter_owned: "Owned Only",
    checking_status: "Checking System Status...",
    systems_operational: "All Systems Operational",
    systems_offline: "Systems Offline / Connection Error",
    systems_degraded: "Some Systems Degraded",
    admin_dash: "Admin Dashboard",
    guide_detail: "Guide Details",
    new_rpg_fan_game: "RHYTHM AND ROLE-PLAYING GAME",
    hero_title: "HOLOLIVE DREAMS",
    hero_subtitle: "Embark on a colorful dreamscape alongside your favorite VTubers. Explore detailed stats, build optimal teams, and customize your showcase profile.",
    view_characters: "View Characters",
    view_guides: "View Guides",
    view_all_articles: "View all articles",
    no_active_team: "No active team. Click to build your team!",
    by_author: "By {author}",
    read_time: "Read Time: {time}",
    leader_skill: "Leader Skill",
    passive_skill: "Passive Skill",
    inactive_skills_title: "Unsatisfied Skill Requirements",
    no_unsatisfied_skills: "No skills are unsatisfied. Your team is performing well!",
    no_active_skills_msg: "No active skills triggered for the current team.",
    add_members_msg: "Add members to the team to check for active Passive Skills.",
    editing_label: "Editing:",
    primary_active_party: "Primary Active Party",
    clear_slots: "Clear Slots",
    my_character_roster: "My Character Roster",
    select_all: "Select All",
    deselect_all: "Deselect All",
    roster_desc: "Configure which characters you own ({owned}/{total}). The recommendation engine will only suggest teams using checked characters.",
    detailed_score_breakdowns: "Detailed Score Calculation Breakdowns",
    detailed_score_desc: "Mathematical formula walkthrough and uptime ratios for the current configuration",
    character: "Character",
    final_stats_header: "Final Stats (S / T / P)",
    power: "Power",
    active_buff: "Active Buff",
    uptime: "Uptime",
    special_buff: "Special Buff",
    score_bonus: "Score Bonus",
    unit_score: "Unit Score",
    total: "TOTAL",
    calculation_math: "Calculation Math",
    final_stats_math: "1. Final Stats Math",
    overall_power_math: "2. Overall Power Math",
    active_uptime_math: "3. Active Skill Uptime Math",
    score_bonus_math: "4. Score Bonus Math",
    final_unit_score_math: "5. Final Unit Score Math",
    applied_buffs: "Applied Buffs",
    triggers_in: "Triggers in",
    trigger_rate: "Trigger Rate",
    uptime_ratio: "Uptime Ratio",
    active: "Active",
    special: "Special",
    total_expected_bonus: "Total Expected Bonus",
    active_contribution: "Active Contribution",
    special_contribution: "Special Contribution",
    sar_contribution: "SAR Contribution",
    team_score_recon: "Team Score Reconciliation",
    outfit_leader: "Outfit Leader",
    best_position: "Best Position",
    effective_magnitude: "Effective Magnitude",
    condition_met: "Condition met",
    condition_not_met: "Condition not met",
    add_members_calc_msg: "Add members to see detailed calculations"
  },
  vi: {
    leader_slot_title: "Trưởng nhóm",
    team_units_title: "Thành viên",
    active_skill: "Kỹ năng Chủ động",
    special_skill: "Kỹ năng Đặc biệt",
    home: "Trang chủ",
    characters: "Nhân vật",
    builder: "Đội hình",
    guides: "Hướng dẫn",
    status: "Trạng thái",
    view_status: "Xem trang trạng thái",
    leader_slot: "Vị trí Trưởng nhóm",
    team_units: "Thành viên đội (Tối đa 5)",
    active_passives: "Kỹ năng Đội hình",
    save_presets: "Lưu cấu hình Đội hình",
    search_placeholder: "Tìm nhân vật theo tên...",
    group: "Thế hệ",
    type: "Hệ",
    all: "Tất cả",
    active_presets_title: "Đội hình hoạt động",
    leader_tag: "Trưởng nhóm",
    member_tag: "Thành viên",
    guides_title: "Hướng dẫn & Chiến thuật",
    guides_page_title: "Hướng dẫn & Blog",
    guides_page_subtitle: "Tìm hiểu chiến thuật, hồ sơ nhân vật và hướng dẫn xây dựng đội hình để tối ưu hóa tiến trình Hololive Dreams.",
    read_more: "Đọc thêm",
    database_title: "Thư viện HoloDreams",
    database_desc: "Xem thông tin chi tiết, chỉ số nhân vật và chi tiết kỹ năng của từng tài năng Hololive.",
    skills_label: "Kỹ năng",
    builder_title: "Xây dựng Đội hình",
    builder_desc: "Nhấn vào ô trống để chọn Trưởng nhóm hoặc Thành viên. Đạt điều kiện để kích hoạt Kỹ năng Bị động.",
    presets_manager: "Quản lý Đội hình mẫu",
    presets_desc: "Chuyển đổi giữa các đội hình mẫu hoặc đặt làm đội hình chính của bạn",
    rename_preset: "Đổi tên",
    copy_preset: "Sao chép",
    reset_preset: "Đặt lại",
    make_active: "Kích hoạt",
    smart_suggest: "Đội hình Đề xuất",
    empty_leader_placeholder: "Nhấp để chọn Trưởng nhóm",
    selecting_leader_placeholder: "Đang chọn Trưởng nhóm...",
    empty_slot_placeholder: "Slot {num}: Nhấp để chọn",
    selecting_slot_placeholder: "Đang chọn Slot {num}...",
    recommended_team_popup_title: "Đội hình Đề xuất Thông minh",
    apply_recommendation: "Áp dụng Đội hình",
    cancel: "Hủy",
    select_char_modal_title: "Chọn nhân vật thêm vào đội",
    filter_owned: "Chỉ nhân vật sở hữu",
    checking_status: "Đang kiểm tra trạng thái...",
    systems_operational: "Hệ thống ổn định",
    systems_offline: "Hệ thống ngoại tuyến / Lỗi kết nối",
    systems_degraded: "Một số hệ thống gặp lỗi",
    admin_dash: "Bảng quản trị",
    guide_detail: "Chi tiết bài viết",
    new_rpg_fan_game: "RPG FAN-GAME MỚI",
    hero_title: "HOLOLIVE DREAMS",
    hero_subtitle: "Khám phá thế giới mộng mơ đầy màu sắc cùng các VTubers yêu thích. Xem thông tin chi tiết, xây dựng đội hình và tùy biến hồ sơ trưng bày.",
    view_characters: "Xem nhân vật",
    view_guides: "Xem bài viết",
    view_all_articles: "Xem tất cả bài viết",
    no_active_team: "Chưa có đội hình chính. Click để xây dựng đội hình!",
    by_author: "Tác giả: {author}",
    read_time: "Thời gian đọc: {time}",
    leader_skill: "Kỹ năng Trưởng nhóm",
    passive_skill: "Kỹ năng Bị động",
    inactive_skills_title: "Kỹ năng chưa thỏa mãn yêu cầu",
    no_unsatisfied_skills: "Không có kỹ năng nào không được thỏa mãn yêu cầu, đội của bạn đang hoạt động tốt.",
    no_active_skills_msg: "Không có kỹ năng kích hoạt cho đội hình hiện tại.",
    add_members_msg: "Thêm thành viên vào đội hình để kiểm tra Kỹ năng Bị động.",
    editing_label: "Đang chỉnh sửa:",
    primary_active_party: "Đội hình hoạt động chính",
    clear_slots: "Làm trống đội",
    my_character_roster: "Danh sách nhân vật sở hữu",
    select_all: "Chọn tất cả",
    deselect_all: "Bỏ chọn tất cả",
    roster_desc: "Chọn nhân vật bạn sở hữu ({owned}/{total}). Bộ đề xuất thông minh sẽ chỉ lập đội bằng nhân vật được chọn.",
    detailed_score_breakdowns: "Bảng phân tích chi tiết tính điểm",
    detailed_score_desc: "Chi tiết công thức toán học và tỷ lệ hoạt động của đội hình hiện tại",
    character: "Nhân vật",
    final_stats_header: "Chỉ số cuối (S / T / P)",
    power: "Lực chiến",
    active_buff: "Buff Chủ động",
    uptime: "Uptime",
    special_buff: "Buff Đặc biệt",
    score_bonus: "Bonus Điểm",
    unit_score: "Điểm Nhân vật",
    total: "TỔNG CỘNG",
    calculation_math: "Phép tính chi tiết",
    final_stats_math: "1. Phép tính chỉ số cuối",
    overall_power_math: "2. Phép tính lực chiến tổng",
    active_uptime_math: "3. Phép tính tỷ lệ uptime kỹ năng",
    score_bonus_math: "4. Phép tính bonus điểm",
    final_unit_score_math: "5. Phép tính điểm nhân vật cuối",
    applied_buffs: "Hiệu ứng áp dụng",
    triggers_in: "Kích hoạt trong",
    trigger_rate: "Tỷ lệ kích hoạt",
    uptime_ratio: "Tỷ lệ hoạt động",
    active: "Chủ động",
    special: "Đặc biệt",
    total_expected_bonus: "Tổng Bonus Dự kiến",
    active_contribution: "Đóng góp kỹ năng Active",
    special_contribution: "Đóng góp hỗ trợ Special",
    sar_contribution: "Đóng góp SAR",
    team_score_recon: "Đối chiếu điểm của đội",
    outfit_leader: "Trưởng trang phục",
    best_position: "Vị trí tối ưu",
    effective_magnitude: "Cường độ thực tế",
    condition_met: "Thỏa điều kiện",
    condition_not_met: "Không thỏa điều kiện",
    add_members_calc_msg: "Thêm thành viên để xem phép tính chi tiết"
  },
  ja: {
    leader_slot_title: "リーダー枠",
    team_units_title: "チームメンバー",
    active_skill: "アクティブスキル",
    special_skill: "スペシャルスキル",
    home: "ホーム",
    characters: "キャラクター",
    builder: "チーム編成",
    guides: "ガイド",
    status: "ステータス",
    view_status: "ステータスページ表示",
    leader_slot: "リーダー枠",
    team_units: "チームメンバー (最大5)",
    active_passives: "アクティブキャラクタースキル",
    save_presets: "編成を保存する",
    search_placeholder: "名前でキャラクターを検索...",
    group: "グループ",
    type: "タイプ",
    all: "すべて",
    active_presets_title: "現在の編成",
    leader_tag: "リーダー",
    member_tag: "メンバー",
    guides_title: "攻略ガイド＆戦略",
    guides_page_title: "ゲームガイド＆ブログ",
    guides_page_subtitle: "ホロライブドリームスの進行を最適化するための戦略、キャラクター情報、チーム編成ガイドを学びましょう。",
    read_more: "詳細を見る",
    database_title: "HoloDreams データベース",
    database_desc: "ホロライブメンバーのプロフィール、ステータス、スキル詳細を閲覧できます。",
    skills_label: "スキル",
    builder_title: "チームビルダー",
    builder_desc: "スロットをクリックしてリーダーやメンバーを配置します。条件を達成してパッシブを有効にしましょう。",
    presets_manager: "プリセット管理",
    presets_desc: "プリセットを切り替えるか、メインデッキとしてアクティブにします",
    rename_preset: "名前変更",
    copy_preset: "コピー",
    reset_preset: "リセット",
    make_active: "アクティブ化",
    smart_suggest: "スマートおすすめ編成",
    empty_leader_placeholder: "クリックしてリーダーを選択",
    selecting_leader_placeholder: "リーダー選択中...",
    empty_slot_placeholder: "スロット {num}: クリックして選択",
    selecting_slot_placeholder: "スロット {num} 選択中...",
    recommended_team_popup_title: "スマートおすすめ編成提案",
    apply_recommendation: "提案を適用",
    cancel: "キャンセル",
    select_char_modal_title: "追加するメンバーを選択",
    filter_owned: "所持済みのみ",
    checking_status: "状態チェック中...",
    systems_operational: "全システム正常稼働中",
    systems_offline: "接続エラー / オフライン",
    systems_degraded: "一部システム障害発生中",
    admin_dash: "管理ダッシュボード",
    guide_detail: "ガイド詳細",
    new_rpg_fan_game: "新作RPGファンゲーム",
    hero_title: "HOLOLIVE DREAMS",
    hero_subtitle: "お気に入りのVTuberたちとカラフルな夢の世界へ旅立とう。詳細なステータスを確認し、最強のチームを編成しよう。",
    view_characters: "キャラクター一覧",
    view_guides: "ガイド一覧",
    view_all_articles: "すべての記事を見る",
    no_active_team: "編成されていません。クリックして編成を始めましょう！",
    by_author: "作成者: {author}",
    read_time: "所要時間: {time}",
    leader_skill: "リーダースキル",
    passive_skill: "パッシブスキル",
    inactive_skills_title: "未発動のスキル条件",
    no_unsatisfied_skills: "条件を満たしていないスキルはありません。チームは最高の状態です！",
    no_active_skills_msg: "現在のチームで発動しているスキルはありません。",
    add_members_msg: "チームメンバーを追加してスキル発動状況を確認しましょう。",
    editing_label: "編集名:",
    primary_active_party: "主要のアクティブパーティ",
    clear_slots: "スロットをクリア",
    my_character_roster: "所持キャラクター一覧",
    select_all: "すべて選択",
    deselect_all: "選択解除",
    roster_desc: "所持しているキャラクターを設定します ({owned}/{total})。おすすめ編成ではチェックしたメンバーのみを使用します。",
    detailed_score_breakdowns: "詳細スコア計算内訳",
    detailed_score_desc: "現在の編成における数学的計算手順と期待稼働率",
    character: "キャラクター",
    final_stats_header: "最終ステータス (S / T / P)",
    power: "総合戦闘力",
    active_buff: "アクティブバフ",
    uptime: "稼働率",
    special_buff: "スペシャルバフ",
    score_bonus: "スコアボーナス",
    unit_score: "ユニットスコア",
    total: "合計",
    calculation_math: "詳細計算式",
    final_stats_math: "1. 最終ステータス計算",
    overall_power_math: "2. 総合戦闘力計算",
    active_uptime_math: "3. アクティブスキル稼働率計算",
    score_bonus_math: "4. スコアボーナス計算",
    final_unit_score_math: "5. 最終ユニットスコア計算",
    applied_buffs: "適用バフ",
    triggers_in: "曲長内のトリガー数",
    trigger_rate: "発動率",
    uptime_ratio: "稼働比率",
    active: "アクティブ",
    special: "スペシャル",
    total_expected_bonus: "期待合計ボーナス",
    active_contribution: "アクティブスキル貢献",
    special_contribution: "スペシャルサポート貢献",
    sar_contribution: "SAR上昇貢献",
    team_score_recon: "チームスコア整合",
    outfit_leader: "衣装リーダー",
    best_position: "最適スロット",
    effective_magnitude: "実効効果量",
    condition_met: "条件成立",
    condition_not_met: "条件不成立",
    add_members_calc_msg: "メンバーを追加して詳細な計算を表示"
  },
  zh: {
    leader_slot_title: "隊長欄位",
    team_units_title: "隊員欄位",
    active_skill: "主動技能",
    special_skill: "特殊技能",
    home: "首頁",
    characters: "角色圖鑑",
    builder: "隊伍編成",
    guides: "攻略指南",
    status: "系統狀態",
    view_status: "查看狀態頁面",
    leader_slot: "隊長欄位",
    team_units: "隊員名單 (最多5名)",
    active_passives: "出戰角色技能",
    save_presets: "儲存隊伍配置",
    search_placeholder: "輸入名字搜尋角色...",
    group: "期數 / 組合",
    type: "屬性",
    all: "全部",
    active_presets_title: "當前配置隊伍",
    leader_tag: "隊長",
    member_tag: "隊員",
    guides_title: "指南與戰術",
    guides_page_title: "遊戲指南與部落格",
    guides_page_subtitle: "學習戰術、角色分析與組隊指南，優化您的 Hololive Dreams 進度。",
    read_more: "閱讀更多",
    database_title: "HoloDreams 數據庫",
    database_desc: "查看每位 Hololive 成員的詳細資料、屬性數值及技能介紹。",
    skills_label: "技能列表",
    builder_title: "隊伍編成器",
    builder_desc: "點選欄位來指派隊長或隊員。符合特定成員要求以觸發被動技能。",
    presets_manager: "隊伍預設管理器",
    presets_desc: "切換隊伍預設或將其設為主要出戰隊伍",
    rename_preset: "重新命名",
    copy_preset: "複製預設",
    reset_preset: "重設欄位",
    make_active: "設為出戰",
    smart_suggest: "智能推薦陣容",
    empty_leader_placeholder: "點擊選擇隊長",
    selecting_leader_placeholder: "正在選擇隊長...",
    empty_slot_placeholder: "位置 {num}: 點擊選擇",
    selecting_slot_placeholder: "正在選擇位置 {num}...",
    recommended_team_popup_title: "智能陣容推薦",
    apply_recommendation: "套用推薦陣容",
    cancel: "取消",
    select_char_modal_title: "選擇要加入的角色",
    filter_owned: "僅顯示已擁有",
    checking_status: "正在檢查系統狀態...",
    systems_operational: "所有系統正常運作",
    systems_offline: "系統斷線 / 連線錯誤",
    systems_degraded: "部分系統運作受阻",
    admin_dash: "管理後台",
    guide_detail: "攻略詳情",
    new_rpg_fan_game: "全新同人RPG遊戲",
    hero_title: "HOLOLIVE DREAMS",
    hero_subtitle: "與你最愛的VTuber一同踏入繽紛的夢境。查看詳細數值，打造完美陣容，定製個人名片。",
    view_characters: "查看角色",
    view_guides: "查看攻略",
    view_all_articles: "查看所有文章",
    no_active_team: "尚未配置出戰隊伍。點擊開始組建！",
    by_author: "作者: {author}",
    read_time: "閱讀時間: {time}",
    leader_skill: "隊長技能",
    passive_skill: "被動技能",
    inactive_skills_title: "未滿足的技能要求",
    no_unsatisfied_skills: "所有技能要求均已滿足。您的隊伍運作良好！",
    no_active_skills_msg: "當前隊伍沒有觸發任何技能。",
    add_members_msg: "新增隊員以檢查被動技能觸發狀況。",
    editing_label: "正在編輯:",
    primary_active_party: "主要出戰隊伍",
    clear_slots: "清除欄位",
    my_character_roster: "擁有角色名冊",
    select_all: "選擇全部",
    deselect_all: "取消全選",
    roster_desc: "配置您所擁有的角色 ({owned}/{total})。智能陣容推薦將僅使用勾選的角色進行組合。",
    detailed_score_breakdowns: "詳細分數計算明細",
    detailed_score_desc: "當前配置的數學公式引導和預期覆蓋率",
    character: "角色",
    final_stats_header: "最終屬性 (S / T / P)",
    power: "綜合戰力",
    active_buff: "主動Buff",
    uptime: "覆蓋率",
    special_buff: "特殊Buff",
    score_bonus: "得分加成",
    unit_score: "單人得分",
    total: "總計",
    calculation_math: "詳細計算公式",
    final_stats_math: "1. 最終屬性計算",
    overall_power_math: "2. 綜合戰力計算",
    active_uptime_math: "3. 主動技能覆蓋率計算",
    score_bonus_math: "4. 得分加成計算",
    final_unit_score_math: "5. 單人得分計算",
    applied_buffs: "已應用Buff",
    triggers_in: "歌曲長度內觸發次數",
    trigger_rate: "觸發概率",
    uptime_ratio: "覆蓋比例",
    active: "主動",
    special: "特殊",
    total_expected_bonus: "預期總加成",
    active_contribution: "主動技能貢獻",
    special_contribution: "特殊支援貢獻",
    sar_contribution: "SAR提升貢獻",
    team_score_recon: "隊伍分數對帳",
    outfit_leader: "服裝隊長",
    best_position: "最佳位置",
    effective_magnitude: "實際效果量",
    condition_met: "條件成立",
    condition_not_met: "條件不成立",
    add_members_calc_msg: "添加成員以查看詳細計算"
  },
  ko: {
    leader_slot_title: "리더 슬롯",
    team_units_title: "팀 멤버",
    active_skill: "액티브 스킬",
    special_skill: "스페셜 스킬",
    home: "홈",
    characters: "캐릭터 도감",
    builder: "팀 편성",
    guides: "공략 가이드",
    status: "시스템 상태",
    view_status: "상태 페이지 보기",
    leader_slot: "리더 슬롯",
    team_units: "팀 멤버 (최대 5명)",
    active_passives: "액티브 캐릭터 스킬",
    save_presets: "팀 편성 저장",
    search_placeholder: "이름으로 캐릭터 검색...",
    group: "기수 / 그룹",
    type: "타입",
    all: "전체",
    active_presets_title: "현재 저장된 편성",
    leader_tag: "리더",
    member_tag: "멤버",
    guides_title: "가이드 및 전략",
    guides_page_title: "게임 가이드 및 블로그",
    guides_page_subtitle: "홀로라이브 드림스 진행을 최적화하기 위한 전략, 캐릭터 정보, 팀 빌딩 가이드를 알아보세요.",
    read_more: "자세히 보기",
    database_title: "HoloDreams 데이터베이스",
    database_desc: "모든 홀로라이브 멤버들의 상세 스탯 및 스킬을 확인하세요.",
    skills_label: "스킬 목록",
    builder_title: "팀 빌더",
    builder_desc: "슬롯을 클릭하여 리더 또는 팀원을 배치합니다. 조건에 맞게 배치하면 패시브 스킬이 발동합니다.",
    presets_manager: "프리셋 매니저",
    presets_desc: "팀 편성을 전환하거나 기본 덱(출전 파티)으로 활성화합니다",
    rename_preset: "이름 변경",
    copy_preset: "복사",
    reset_preset: "초기화",
    make_active: "출전 설정",
    smart_suggest: "스마트 추천 편성",
    empty_leader_placeholder: "클릭하여 리더 선택",
    selecting_leader_placeholder: "리더 선택 중...",
    empty_slot_placeholder: "슬롯 {num}: 클릭하여 선택",
    selecting_slot_placeholder: "슬롯 {num} 선택 중...",
    recommended_team_popup_title: "스마트 팀 추천",
    apply_recommendation: "추천 편성 적용",
    cancel: "취소",
    select_char_modal_title: "추가할 캐릭터 선택",
    filter_owned: "보유 캐릭터만",
    checking_status: "시스템 상태 확인 중...",
    systems_operational: "모든 시스템 정상 작동 중",
    systems_offline: "오프라인 / 연결 오류",
    systems_degraded: "일부 시스템 장애 발생",
    admin_dash: "관리자 대시보드",
    guide_detail: "가이드 상세",
    new_rpg_fan_game: "새로운 RPG 팬 게임",
    hero_title: "HOLOLIVE DREAMS",
    hero_subtitle: "가장 좋아하는 VTuber들과 함께 알록달록한 꿈의 세계로 떠나보세요. 상세 스탯을 탐색하고 팀을 최적화하세요.",
    view_characters: "캐릭터 보기",
    view_guides: "가이드 보기",
    view_all_articles: "모든 가이드 보기",
    no_active_team: "활성화된 팀이 없습니다. 클릭하여 나만의 팀을 만들어보세요!",
    by_author: "작성자: {author}",
    read_time: "소요 시간: {time}",
    leader_skill: "리더 스킬",
    passive_skill: "패시브 스킬",
    inactive_skills_title: "미발동 스킬 조건",
    no_unsatisfied_skills: "불만족된 스킬 조건이 없습니다. 팀이 완벽하게 가동 중입니다!",
    no_active_skills_msg: "현재 편성된 팀에 활성화된 스킬이 없습니다.",
    add_members_msg: "팀원을 배치하여 패시브 스킬 조건을 확인해보세요.",
    editing_label: "편집 중:",
    primary_active_party: "기본 출전 파티",
    clear_slots: "슬롯 초기화",
    my_character_roster: "보유 캐릭터 목록",
    select_all: "전체 선택",
    deselect_all: "전체 해제",
    roster_desc: "보유한 캐릭터를 설정합니다 ({owned}/{total}). 스마트 추천 엔진은 체크된 캐릭터만 사용하여 팀을 제안합니다.",
    detailed_score_breakdowns: "상세 점수 계산 분석",
    detailed_score_desc: "현재 구성을 위한 수학적 공식 안내 및 예상 가동률",
    character: "캐릭터",
    final_stats_header: "최종 능력치 (S / T / P)",
    power: "종합 전투력",
    active_buff: "액티브 버프",
    uptime: "가동률",
    special_buff: "스페셜 버프",
    score_bonus: "점수 보너스",
    unit_score: "유닛 점수",
    total: "합계",
    calculation_math: "상세 계산법",
    final_stats_math: "1. 최종 능력치 계산",
    overall_power_math: "2. 종합 전투력 계산",
    active_uptime_math: "3. 액티브 스킬 가동률 계산",
    score_bonus_math: "4. 점수 보너스 계산",
    final_unit_score_math: "5. 최종 유닛 점수 계산",
    applied_buffs: "적용된 버프",
    triggers_in: "곡 길이 내 발동 횟수",
    trigger_rate: "발동률",
    uptime_ratio: "가동 비율",
    active: "액티브",
    special: "스페셜",
    total_expected_bonus: "예상 총 보너스",
    active_contribution: "액티브 스킬 기여",
    special_contribution: "스페셜 지원 기여",
    sar_contribution: "SAR 상승 기여",
    team_score_recon: "팀 점수 대조",
    outfit_leader: "의상 리더",
    best_position: "최적 슬롯",
    effective_magnitude: "실질 효과량",
    condition_met: "조건 충족",
    condition_not_met: "조건 미충족",
    add_members_calc_msg: "멤버를 추가하여 상세 계산 보기"
  },
  de: {
    leader_slot_title: "Leader-Slot",
    team_units_title: "Team-Mitglieder",
    active_skill: "Aktive Fähigkeit",
    special_skill: "Spezialfähigkeit",
    home: "Startseite",
    characters: "Charaktere",
    builder: "Teambildung",
    guides: "Guides",
    status: "Status",
    view_status: "Statusseite anzeigen",
    leader_slot: "Anführer-Slot",
    team_units: "Teameinheiten (Max 5)",
    active_passives: "Aktive Charakterfähigkeiten",
    save_presets: "Preset-Konfiguration speichern",
    search_placeholder: "Charaktere nach Name suchen...",
    group: "Gruppe",
    type: "Typ",
    all: "Alle",
    active_presets_title: "Aktive Presets",
    leader_tag: "Anführer",
    member_tag: "Mitglied",
    guides_title: "Guides & Strategien",
    guides_page_title: "Spiele-Guides & Blog",
    guides_page_subtitle: "Lerne Strategien, Charakter-Einblicke und Team-Builds, um deinen Fortschritt in Hololive Dreams zu optimieren.",
    read_more: "Mehr lesen",
    database_title: "HoloDreams-Datenbank",
    database_desc: "Detaillierte Profilinformationen, Charakterwerte und Skill-Details für jedes Holo-Talent ansehen.",
    skills_label: "Fähigkeiten",
    builder_title: "Teambuilder",
    builder_desc: "Klicke auf einen Slot, um Mitglieder oder den Anführer zuzuweisen. Erfülle Bedingungen für passive Skills.",
    presets_manager: "Preset-Manager",
    presets_desc: "Wechsle Presets oder aktiviere eines als Hauptdeck (Aktive Party)",
    rename_preset: "Umbenennen",
    copy_preset: "Kopieren",
    reset_preset: "Zurücksetzen",
    make_active: "Aktivieren",
    smart_suggest: "Teamebene vorschlagen",
    empty_leader_placeholder: "Klicken, um Anführer zu wählen",
    selecting_leader_placeholder: "Wähle Anführer...",
    empty_slot_placeholder: "Slot {num}: Klicken zum Wählen",
    selecting_slot_placeholder: "Wähle Slot {num}...",
    recommended_team_popup_title: "Smarte Team-Empfehlung",
    apply_recommendation: "Empfehlung anwenden",
    cancel: "Abbrechen",
    select_char_modal_title: "Charakter zum Hinzufügen wählen",
    filter_owned: "Nur im Besitz",
    checking_status: "Prüfe Systemstatus...",
    systems_operational: "Alle Systeme betriebsbereit",
    systems_offline: "Systeme offline / Verbindungsfehler",
    systems_degraded: "Einige Systeme beeinträchtigt",
    admin_dash: "Admin-Dashboard",
    guide_detail: "Guide-Details",
    new_rpg_fan_game: "NEUES RPG FAN-SPIEL",
    hero_title: "HOLOLIVE DREAMS",
    hero_subtitle: "Begib dich auf eine bunte Traumlandschaft an der Seite deiner Lieblings-VTuber. Erkunde Statistiken und erstelle Teams.",
    view_characters: "Charaktere ansehen",
    view_guides: "Guides ansehen",
    view_all_articles: "Alle Artikel anzeigen",
    no_active_team: "Kein aktives Team. Klicke, um ein Team zu erstellen!",
    by_author: "Von {author}",
    read_time: "Lesezeit: {time}",
    leader_skill: "Anführer-Skill",
    passive_skill: "Passiver Skill",
    inactive_skills_title: "Unerfüllte Skill-Bedingungen",
    no_unsatisfied_skills: "Alle Skill-Bedingungen sind erfüllt. Ihr Team läuft perfekt!",
    no_active_skills_msg: "Keine aktiven Skills für das aktuelle Team.",
    add_members_msg: "Füge Mitglieder hinzu, um aktive passive Fähigkeiten zu prüfen.",
    editing_label: "Bearbeiten:",
    primary_active_party: "Haupt-Aktiv-Gruppe",
    clear_slots: "Slots leeren",
    my_character_roster: "Mein Roster",
    select_all: "Alle auswählen",
    deselect_all: "Auswahl aufheben",
    roster_desc: "Besitz ({owned}/{total}). Empfehlung schlägt nur Teams mit markierten Charakteren vor.",
    detailed_score_breakdowns: "Detaillierte Score-Berechnung",
    detailed_score_desc: "Mathematische Formel und Uptime-Verhältnisse für das aktuelle Setup",
    character: "Charakter",
    final_stats_header: "Finale Stats (S / T / P)",
    power: "Kampfkraft",
    active_buff: "Aktiver Buff",
    uptime: "Uptime",
    special_buff: "Spezial-Buff",
    score_bonus: "Score-Bonus",
    unit_score: "Einheiten-Score",
    total: "GESAMT",
    calculation_math: "Detaillierte Berechnung",
    final_stats_math: "1. Finale Stats Berechnung",
    overall_power_math: "2. Gesamtkraft Berechnung",
    active_uptime_math: "3. Aktive Skill Uptime Berechnung",
    score_bonus_math: "4. Score-Bonus Berechnung",
    final_unit_score_math: "5. Finale Einheiten-Score Berechnung",
    applied_buffs: "Angewandte Buffs",
    triggers_in: "Trigger in",
    trigger_rate: "Trigger-Rate",
    uptime_ratio: "Uptime-Verhältnis",
    active: "Aktiv",
    special: "Spezial",
    total_expected_bonus: "Erwarteter Gesamtbonus",
    active_contribution: "Beitrag aktiver Fähigkeit",
    special_contribution: "Spezial-Unterstützungsbeitrag",
    sar_contribution: "SAR-Anstiegsbeitrag",
    team_score_recon: "Team-Score-Abgleich",
    outfit_leader: "Outfit-Leiter",
    best_position: "Bester Slot",
    effective_magnitude: "Effektive Stärke",
    condition_met: "Bedingung erfüllt",
    condition_not_met: "Bedingung nicht erfüllt",
    add_members_calc_msg: "Mitglieder hinzufügen, um detaillierte Berechnungen anzuzeigen"
  },
  es: {
    leader_slot_title: "Casilla del Líder",
    team_units_title: "Miembros del Equipo",
    active_skill: "Habilidad Activa",
    special_skill: "Habilidad Especial",
    home: "Inicio",
    characters: "Personajes",
    builder: "Creador de Equipos",
    guides: "Guías",
    status: "Estado",
    view_status: "Ver página de estado",
    leader_slot: "Ranura de Líder",
    team_units: "Unidades de Equipo (Máx. 5)",
    active_passives: "Habilidades de Personajes Activos",
    save_presets: "Guardar Configuración",
    search_placeholder: "Buscar personajes...",
    group: "Grupo",
    type: "Tipo",
    all: "Todos",
    active_presets_title: "Ajustes Activos",
    leader_tag: "Líder",
    member_tag: "Miembro",
    guides_title: "Guías & Estrategias",
    guides_page_title: "Guías de juego y blog",
    guides_page_subtitle: "Aprende estrategias, información sobre personajes y guías de equipo para optimizar tu progreso en Hololive Dreams.",
    read_more: "Leer más",
    database_title: "Base de Datos",
    database_desc: "Ver perfiles detallados, estadísticas y habilidades de cada talento de Hololive.",
    skills_label: "Habilidades",
    builder_title: "Creador de Equipos",
    builder_desc: "Haz clic en una ranura para asignar miembros. Cumple requisitos para activar habilidades pasivas.",
    presets_manager: "Gestor de Ajustes",
    presets_desc: "Cambia de ajustes o activa uno como baraja principal",
    rename_preset: "Renombrar",
    copy_preset: "Copiar",
    reset_preset: "Reiniciar",
    make_active: "Activar",
    smart_suggest: "Sugerencia Inteligente",
    empty_leader_placeholder: "Clic para seleccionar Líder",
    selecting_leader_placeholder: "Seleccionando Líder...",
    empty_slot_placeholder: "Ranura {num}: Clic para seleccionar",
    selecting_slot_placeholder: "Seleccionando Ranura {num}...",
    recommended_team_popup_title: "Recomendación de Equipo",
    apply_recommendation: "Aplicar Recomendación",
    cancel: "Cancelar",
    select_char_modal_title: "Seleccionar personaje para añadir",
    filter_owned: "Solo en posesión",
    checking_status: "Verificando estado del sistema...",
    systems_operational: "Todos los sistemas operativos",
    systems_offline: "Sistemas sin conexión / Error de conexión",
    systems_degraded: "Algunos sistemas degradados",
    admin_dash: "Panel de Admin",
    guide_detail: "Detalles de Guía",
    new_rpg_fan_game: "NUEVO FAN-GAME RPG",
    hero_title: "HOLOLIVE DREAMS",
    hero_subtitle: "Embárcate en un colorido paisaje de ensueño con tus VTubers favoritos. Explora estadísticas y crea equipos.",
    view_characters: "Ver Personajes",
    view_guides: "Ver Guías",
    view_all_articles: "Ver todos los artículos",
    no_active_team: "Sin equipo activo. ¡Clic para crear tu equipo!",
    by_author: "Por {author}",
    read_time: "Lectura: {time}",
    leader_skill: "Habilidad de Líder",
    passive_skill: "Habilidad Pasiva",
    inactive_skills_title: "Requisitos de Habilidad no Cumplidos",
    no_unsatisfied_skills: "Todos los requisitos de habilidad están cumplidos. ¡Tu equipo funciona perfectamente!",
    no_active_skills_msg: "Ninguna habilidad activa activada para el equipo actual.",
    add_members_msg: "Añade miembros al equipo para verificar las habilidades pasivas.",
    editing_label: "Editando:",
    primary_active_party: "Grupo Activo Principal",
    clear_slots: "Limpiar ranuras",
    my_character_roster: "Mi Lista",
    select_all: "Seleccionar todo",
    deselect_all: "Deseleccionar todo",
    roster_desc: "Posesión ({owned}/{total}). Recomendación solo sugerirá marcados.",
    detailed_score_breakdowns: "Desglose Detallado de Cálculos",
    detailed_score_desc: "Fórmula matemática y ratios de tiempo de actividad de la configuración actual",
    character: "Personaje",
    final_stats_header: "Stats Finales (S / T / P)",
    power: "Poder General",
    active_buff: "Buff Activo",
    uptime: "Uptime",
    special_buff: "Buff Especial",
    score_bonus: "Bono de Score",
    unit_score: "Score de Unidad",
    total: "TOTAL",
    calculation_math: "Cálculo Detallado",
    final_stats_math: "1. Cálculo de Stats Finales",
    overall_power_math: "2. Cálculo de Poder General",
    active_uptime_math: "3. Cálculo de Uptime de Habilidad Activa",
    score_bonus_math: "4. Cálculo de Bono de Score",
    final_unit_score_math: "5. Cálculo de Score de Unidad Final",
    applied_buffs: "Buffs Aplicados",
    triggers_in: "Activaciones en",
    trigger_rate: "Tasa de Activación",
    uptime_ratio: "Ratio de Uptime",
    active: "Activo",
    special: "Especial",
    total_expected_bonus: "Bono Total Esperado",
    active_contribution: "Contribución de habilidad activa",
    special_contribution: "Contribución de apoyo especial",
    sar_contribution: "Contribución de aumento SAR",
    team_score_recon: "Conciliación de puntaje del equipo",
    outfit_leader: "Líder de atuendo",
    best_position: "Mejor posición",
    effective_magnitude: "Magnitud efectiva",
    condition_met: "Condición cumplida",
    condition_not_met: "Condición no cumplida",
    add_members_calc_msg: "Añadir miembros para ver los cálculos detallados"
  },
  fr: {
    leader_slot_title: "Emplacement du Leader",
    team_units_title: "Membres de l'Équipe",
    active_skill: "Compétence Active",
    special_skill: "Compétence Spéciale",
    home: "Accueil",
    characters: "Personnages",
    builder: "Composition",
    guides: "Guides",
    status: "Statut",
    view_status: "Voir la page de statut",
    leader_slot: "Emplacement Leader",
    team_units: "Membres de l'équipe (Max 5)",
    active_passives: "Compétences de Personnages Actifs",
    save_presets: "Sauvegarder",
    search_placeholder: "Rechercher...",
    group: "Groupe",
    type: "Type",
    all: "Tous",
    active_presets_title: "Compositions actives",
    leader_tag: "Leader",
    member_tag: "Membre",
    guides_title: "Guides & Stratégies",
    guides_page_title: "Guides de jeu & Blog",
    guides_page_subtitle: "Apprenez des stratégies, des informations sur les personnages et des guides d'équipe pour optimiser votre progression dans Hololive Dreams.",
    read_more: "Lire la suite",
    database_title: "Base de données",
    database_desc: "Fiches détaillées, statistiques et compétences pour chaque talent Hololive.",
    skills_label: "Compétences",
    builder_title: "Création d'équipe",
    builder_desc: "Assignez le Leader ou des membres. Remplissez les conditions pour activer les passifs.",
    presets_manager: "Gestionnaire de presets",
    presets_desc: "Changez de preset ou activez-en un comme équipe active",
    rename_preset: "Renommer",
    copy_preset: "Copier",
    reset_preset: "Réinitialiser",
    make_active: "Activer",
    smart_suggest: "Suggestion Intelligente",
    empty_leader_placeholder: "Cliquer pour choisir un Leader",
    selecting_leader_placeholder: "Sélection du Leader...",
    empty_slot_placeholder: "Slot {num}: Cliquer pour choisir",
    selecting_slot_placeholder: "Sélection du Slot {num}...",
    recommended_team_popup_title: "Suggestion d'Équipe",
    apply_recommendation: "Appliquer la suggestion",
    cancel: "Annuler",
    select_char_modal_title: "Sélectionner un personnage",
    filter_owned: "Possédé uniquement",
    checking_status: "Vérification du statut du système...",
    systems_operational: "Tous les systèmes sont opérationnels",
    systems_offline: "Systèmes hors ligne",
    systems_degraded: "Certains systèmes sont dégradés",
    admin_dash: "Tableau de bord",
    guide_detail: "Détails du Guide",
    new_rpg_fan_game: "NOUVEAU RPG FAN-GAME",
    hero_title: "HOLOLIVE DREAMS",
    hero_subtitle: "Partez pour un monde onirique coloré aux côtés de vos VTubers préférés. Explorez et créez l'équipe parfaite.",
    view_characters: "Voir les Personnages",
    view_guides: "Voir les Guides",
    view_all_articles: "Voir tous les articles",
    no_active_team: "Aucune équipe active. Cliquez pour en créer une !",
    by_author: "Par {author}",
    read_time: "Lecture: {time}",
    leader_skill: "Compétence de Chef",
    passive_skill: "Compétence Passive",
    inactive_skills_title: "Exigences de Compétence Non Remplies",
    no_unsatisfied_skills: "Toutes les conditions de compétence sont remplies. Votre équipe fonctionne parfaitement !",
    no_active_skills_msg: "Aucune compétence active déclenchée pour l'équipe actuelle.",
    add_members_msg: "Ajoutez des membres à l'équipe pour vérifier les passifs.",
    editing_label: "Édition :",
    primary_active_party: "Équipe Active Principale",
    clear_slots: "Vider les emplacements",
    my_character_roster: "Mon Catalogue",
    select_all: "Tout Sélectionner",
    deselect_all: "Tout Désélectionner",
    roster_desc: "Possédé ({owned}/{total}). La suggestion n'inclut que les cochés.",
    detailed_score_breakdowns: "Détails du Calcul du Score",
    detailed_score_desc: "Formule mathématique et ratios d'uptime pour la configuration actuelle",
    character: "Personnage",
    final_stats_header: "Stats Finales (S / T / P)",
    power: "Puissance Globale",
    active_buff: "Buff Actif",
    uptime: "Uptime",
    special_buff: "Buff Spécial",
    score_bonus: "Bonus de Score",
    unit_score: "Score d'Unité",
    total: "TOTAL",
    calculation_math: "Calcul Détaillé",
    final_stats_math: "1. Calcul des Stats Finales",
    overall_power_math: "2. Calcul de la Puissance Globale",
    active_uptime_math: "3. Calcul de l'Uptime de Compétence Active",
    score_bonus_math: "4. Calcul du Bonus de Score",
    final_unit_score_math: "5. Calcul de Score d'Unité Final",
    applied_buffs: "Buffs Appliqués",
    triggers_in: "Déclenchements en",
    trigger_rate: "Taux de Déclenchement",
    uptime_ratio: "Ratio d'Uptime",
    active: "Actif",
    special: "Spécial",
    total_expected_bonus: "Bonus Total Attendu",
    active_contribution: "Contribution de la compétence active",
    special_contribution: "Contribution du support spécial",
    sar_contribution: "Contribution SAR",
    team_score_recon: "Rapprochement du score d'équipe",
    outfit_leader: "Leader de costume",
    best_position: "Meilleur emplacement",
    effective_magnitude: "Magnitude effective",
    condition_met: "Condition remplie",
    condition_not_met: "Condition non remplie",
    add_members_calc_msg: "Ajouter des membres pour voir les calculs détaillés"
  },
  th: {
    leader_slot_title: "ช่องหัวหน้าทีม",
    team_units_title: "สมาชิกในทีม",
    active_skill: "สกิลใช้งาน",
    special_skill: "สกิลพิเศษ",
    home: "หน้าแรก",
    characters: "ตัวละคร",
    builder: "จัดทีม",
    guides: "คู่มือ",
    status: "สถานะระบบ",
    view_status: "ดูหน้าสถานะ",
    leader_slot: "ช่องหัวหน้าทีม",
    team_units: "สมาชิกทีม (สูงสุด 5)",
    active_passives: "สกิลของตัวละครที่เปิดใช้งาน",
    save_presets: "บันทึกทีม",
    search_placeholder: "ค้นหา...",
    group: "รุ่น / กลุ่ม",
    type: "ประเภท",
    all: "ทั้งหมด",
    active_presets_title: "ทีมที่ใช้งานอยู่",
    leader_tag: "หัวหน้า",
    member_tag: "สมาชิก",
    guides_title: "คู่มือและกลยุทธ์",
    guides_page_title: "คู่มือเกมและบล็อก",
    guides_page_subtitle: "เรียนรู้กลยุทธ์ ข้อมูลเชิงลึกของตัวละคร และแนวทางการสร้างทีมเพื่อเพิ่มประสิทธิภาพความก้าวหน้าใน Hololive Dreams",
    read_more: "อ่านเพิ่มเติม",
    database_title: "ฐานข้อมูล",
    database_desc: "ประวัติอย่างละเอียด ค่าสถานะตัวละคร และรายละเอียดสกิลของสมาชิก Hololive ทุกคน",
    skills_label: "สกิล",
    builder_title: "จัดทีม",
    builder_desc: "คลิกจัดวางหัวหน้าหรือสมาชิกทีม ทำตามเงื่อนไขเพื่อเปิดสกิลติดตัว",
    presets_manager: "จัดการทีมพรีเซ็ต",
    presets_desc: "สลับพรีเซ็ตทีมหรือตั้งค่าเป็นทีมหลัก",
    rename_preset: "เปลี่ยนชื่อ",
    copy_preset: "คัดลอก",
    reset_preset: "รีเซ็ต",
    make_active: "ตั้งใช้งาน",
    smart_suggest: "แนะนำจัดทีมอัจฉริยะ",
    empty_leader_placeholder: "คลิกเพื่อเลือกหัวหน้าทีม",
    selecting_leader_placeholder: "กำลังเลือกหัวหน้า...",
    empty_slot_placeholder: "ช่อง {num}: คลิกเพื่อเลือก",
    selecting_slot_placeholder: "กำลังเลือกช่อง {num}...",
    recommended_team_popup_title: "แนะนำจัดทีม",
    apply_recommendation: "ใช้ทีมแนะนำ",
    cancel: "ยกเลิก",
    select_char_modal_title: "เลือกตัวละคร",
    filter_owned: "เฉพาะที่มีอยู่",
    checking_status: "กำลังตรวจสอบสถานะระบบ...",
    systems_operational: "ทุกระบบทำงานปกติ",
    systems_offline: "ระบบออฟไลน์",
    systems_degraded: "บางระบบทำงานได้ไม่ดี",
    admin_dash: "ระบบหลังบ้าน",
    guide_detail: "รายละเอียดคู่มือ",
    new_rpg_fan_game: "เกมแฟนเมด RPG ใหม่",
    hero_title: "HOLOLIVE DREAMS",
    hero_subtitle: "เริ่มต้นการเดินทางในโลกแห่งความฝันไปกับ VTuber ที่คุณชื่นชอบ จัดทีมและตื่นตาตื่นใจไปกับพลังของพวกเธอ",
    view_characters: "ดูตัวละคร",
    view_guides: "ดูคู่มือ",
    view_all_articles: "ดูบทความทั้งหมด",
    no_active_team: "ไม่มีทีมหลักที่ใช้งาน คลิกเพื่อสร้างทีมหลักของคุณ!",
    by_author: "โดย {author}",
    read_time: "อ่าน: {time}",
    leader_skill: "สกิลหัวหน้าทีม",
    passive_skill: "สกิลติดตัว",
    inactive_skills_title: "สกิลที่ยังไม่เปิดใช้งาน",
    no_unsatisfied_skills: "เงื่อนไขสกิลทั้งหมดได้รับการเปิดใช้งานแล้ว ทีมของคุณพร้อมลุย!",
    no_active_skills_msg: "ไม่มีสกิลที่ทำงานอยู่ในขณะนี้",
    add_members_msg: "เพิ่มสมาชิกทีมเพื่อตรวจสอบการทำงานของสกิลติดตัว",
    editing_label: "กำลังแก้ไข:",
    primary_active_party: "ทีมหลักที่ใช้งาน",
    clear_slots: "ล้างช่องข้อมูล",
    my_character_roster: "รายชื่อของฉัน",
    select_all: "เลือกทั้งหมด",
    deselect_all: "ยกเลิกการเลือกทั้งหมด",
    roster_desc: "มี ({owned}/{total}) ระบบจะแนะนำเฉพาะตัวละครที่เลือก",
    detailed_score_breakdowns: "รายละเอียดการคำนวณคะแนน",
    detailed_score_desc: "สูตรคณิตศาสตร์และอัตราการทำงานสำหรับทีมปัจจุบัน",
    character: "ตัวละคร",
    final_stats_header: "ค่าสถานะสุดท้าย (S / T / P)",
    power: "พลังโดยรวม",
    active_buff: "บัฟแอคทีฟ",
    uptime: "เวลาทำงาน",
    special_buff: "บัฟพิเศษ",
    score_bonus: "โบนัสคะแนน",
    unit_score: "คะแนนตัวละคร",
    total: "ทั้งหมด",
    calculation_math: "การคำนวณโดยละเอียด",
    final_stats_math: "1. การคำนวณค่าสถานะสุดท้าย",
    overall_power_math: "2. การคำนวณพลังโดยรวม",
    active_uptime_math: "3. การคำนวณเวลาทำงานสกิลแอคทีฟ",
    score_bonus_math: "4. การคำนวณโบนัสคะแนน",
    final_unit_score_math: "5. การคำนวณคะแนนตัวละครสุดท้าย",
    applied_buffs: "บัฟที่แสดงผล",
    triggers_in: "การทำงานใน",
    trigger_rate: "อัตราการทำงาน",
    uptime_ratio: "สัดส่วนเวลาทำงาน",
    active: "แอคทีฟ",
    special: "พิเศษ",
    total_expected_bonus: "โบนัสรวมที่คาดหวัง",
    active_contribution: "การมีส่วนร่วมของสกิลแอคทีฟ",
    special_contribution: "การสนับสนุนสกิลพิเศษ",
    sar_contribution: "การมีส่วนร่วม SAR",
    team_score_recon: "การตรวจสอบคะแนนทีม",
    outfit_leader: "ลีดเดอร์ชุด",
    best_position: "ตำแหน่งที่ดีที่สุด",
    effective_magnitude: "ขนาดผลจริง",
    condition_met: "เงื่อนไขผ่าน",
    condition_not_met: "เงื่อนไขไม่ผ่าน",
    add_members_calc_msg: "เพิ่มสมาชิกเพื่อแสดงการคำนวณโดยละเอียด"
  },
  pt: {
    leader_slot_title: "Espaço do Líder",
    team_units_title: "Membros da Equipe",
    active_skill: "Habilidade Ativa",
    special_skill: "Habilidade Especial",
    home: "Início",
    characters: "Personagens",
    builder: "Criador de Equipa",
    guides: "Guias",
    status: "Estado",
    view_status: "Ver página de estado",
    leader_slot: "Slot de Líder",
    team_units: "Unidades de Equipa (Máx 5)",
    active_passives: "Habilidades de Personagens Ativos",
    save_presets: "Salvar Presets",
    search_placeholder: "Procurar...",
    group: "Grupo",
    type: "Tipo",
    all: "Todos",
    active_presets_title: "Equipas Ativas",
    leader_tag: "Líder",
    member_tag: "Membro",
    guides_title: "Guias & Estratégias",
    guides_page_title: "Guias de Jogo & Blog",
    guides_page_subtitle: "Aprenda estratégias, informações sobre personagens e guias de equipe para otimizar seu progresso no Hololive Dreams.",
    read_more: "Ler mais",
    database_title: "Base de Dados",
    database_desc: "Ver perfis detalhados, estatísticas e habilidades para cada talento Hololive.",
    skills_label: "Habilidades",
    builder_title: "Criador de Equipa",
    builder_desc: "Clique num slot para atribuir membros. Complete requisitos para ativar as passivas.",
    presets_manager: "Gestor de Equipas",
    presets_desc: "Alterne entre equipas ou ative uma como equipa principal",
    rename_preset: "Renombrar",
    copy_preset: "Copiar",
    reset_preset: "Repor",
    make_active: "Ativar",
    smart_suggest: "Sugestão Inteligente",
    empty_leader_placeholder: "Clique para selecionar Líder",
    selecting_leader_placeholder: "A selecionar Líder...",
    empty_slot_placeholder: "Slot {num}: Clique para selecionar",
    selecting_slot_placeholder: "A selecionar Slot {num}...",
    recommended_team_popup_title: "Recomendação de Equipa",
    apply_recommendation: "Aplicar Recomendação",
    cancel: "Cancelar",
    select_char_modal_title: "Selecionar personagem",
    filter_owned: "Apenas em posse",
    checking_status: "Verificando status...",
    systems_operational: "Todos os sistemas operacionais",
    systems_offline: "Sistemas offline",
    systems_degraded: "Alguns sistemas degradados",
    admin_dash: "Painel Admin",
    guide_detail: "Detalhes do Guia",
    new_rpg_fan_game: "NOVO JOGO FAN-GAME RPG",
    hero_title: "HOLOLIVE DREAMS",
    hero_subtitle: "Embarque num colorido mundo onírico com as suas VTubers favoritas. Explore status e monte equipas.",
    view_characters: "Ver Personagens",
    view_guides: "Ver Guias",
    view_all_articles: "Ver todos os artigos",
    no_active_team: "Sem equipa ativa. Clique para montar uma equipa!",
    by_author: "Por {author}",
    read_time: "Leitura: {time}",
    leader_skill: "Habilidade de Líder",
    passive_skill: "Habilidade Passiva",
    inactive_skills_title: "Requisitos de Habilidade não Cumpridos",
    no_unsatisfied_skills: "Todos os requisitos de habilidade foram cumpridos. A sua equipa está a funcionar perfeitamente!",
    no_active_skills_msg: "Nenhuma habilidade ativa ativada para o grupo atual.",
    add_members_msg: "Adicione membros ao grupo para verificar as passivas.",
    editing_label: "Editando:",
    primary_active_party: "Equipa Ativa Principal",
    clear_slots: "Limpar Slots",
    my_character_roster: "Meu Catálogo",
    select_all: "Selecionar Todos",
    deselect_all: "Desmarcar Todos",
    roster_desc: "Posse ({owned}/{total}). Sugestão só propõe assinalados.",
    detailed_score_breakdowns: "Detalhamento de Cálculo de Pontuação",
    detailed_score_desc: "Fórmula matemática e proporção de uptime para o setup atual",
    character: "Personagem",
    final_stats_header: "Stats Finais (S / T / P)",
    power: "Poder Geral",
    active_buff: "Buff Ativo",
    uptime: "Uptime",
    special_buff: "Buff Especial",
    score_bonus: "Bônus de Pontos",
    unit_score: "Pontuação de Unidade",
    total: "TOTAL",
    calculation_math: "Cálculo Detalhado",
    final_stats_math: "1. Cálculo de Stats Finais",
    overall_power_math: "2. Cálculo de Poder Geral",
    active_uptime_math: "3. Cálculo de Uptime de Habilidade Ativa",
    score_bonus_math: "4. Cálculo de Bônus de Pontos",
    final_unit_score_math: "5. Cálculo de Pontuação de Unidade Final",
    applied_buffs: "Buffs Aplicados",
    triggers_in: "Ativações em",
    trigger_rate: "Taxa de Ativação",
    uptime_ratio: "Proporção de Uptime",
    active: "Ativo",
    special: "Especial",
    total_expected_bonus: "Bônus Total Esperado",
    active_contribution: "Contribuição da habilidade ativa",
    special_contribution: "Contribuição de suporte especial",
    sar_contribution: "Contribuição SAR",
    team_score_recon: "Conciliação de pontuação do time",
    outfit_leader: "Líder de visual",
    best_position: "Melhor posição",
    effective_magnitude: "Magnitude efetiva",
    condition_met: "Condição atendida",
    condition_not_met: "Condição não atendida",
    add_members_calc_msg: "Adicione membros para ver os cálculos detalhados"
  },
  ru: {
    leader_slot_title: "Слот лидера",
    team_units_title: "Члены команды",
    active_skill: "Активный навык",
    special_skill: "Специальный навык",
    home: "Главная",
    characters: "Персонажи",
    builder: "Отряд",
    guides: "Руководства",
    status: "Статус",
    view_status: "Посмотреть страницу статуса",
    leader_slot: "Слот Лидера",
    team_units: "Члены отряда (Макс. 5)",
    active_passives: "Активные навыки персонажей",
    save_presets: "Сохранить отряды",
    search_placeholder: "Поиск...",
    group: "Поколение",
    type: "Тип",
    all: "Все",
    active_presets_title: "Сохраненные отряды",
    leader_tag: "Лидер",
    member_tag: "Участник",
    guides_title: "Руководства и тактики",
    guides_page_title: "Игровые руководства и блог",
    guides_page_subtitle: "Изучите стратегии, информацию о персонажах и руководства по сборке отрядов для оптимизации вашего прогресса в Hololive Dreams.",
    read_more: "Читать далее",
    database_title: "База данных",
    database_desc: "Подробные профили, характеристики и навыки каждого таланта Hololive.",
    skills_label: "Навыки",
    builder_title: "Редактор отряда",
    builder_desc: "Нажмите на слот, чтобы назначить Лидера или членов отряда.",
    presets_manager: "Шаблоны отрядов",
    presets_desc: "Переключайте шаблоны или активируйте один как основной отряд",
    rename_preset: "Переименовать",
    copy_preset: "Копировать",
    reset_preset: "Сбросить",
    make_active: "Активировать",
    smart_suggest: "Умный подбор отряда",
    empty_leader_placeholder: "Нажмите для выбора Лидера",
    selecting_leader_placeholder: "Выбор Лидера...",
    empty_slot_placeholder: "Слот {num}: Нажмите для выбора",
    selecting_slot_placeholder: "Выбор слота {num}...",
    recommended_team_popup_title: "Рекомендация отряда",
    apply_recommendation: "Применить сборку",
    cancel: "Отмена",
    select_char_modal_title: "Выберите персонажа",
    filter_owned: "Только имеющиеся",
    checking_status: "Проверка статуса систем...",
    systems_operational: "Все системы работают нормально",
    systems_offline: "Системы оффлайн",
    systems_degraded: "Некоторые системы перегружены",
    admin_dash: "Панель администратора",
    guide_detail: "Детали руководства",
    new_rpg_fan_game: "НОВАЯ ФАН-ИГРА RPG",
    hero_title: "HOLOLIVE DREAMS",
    hero_subtitle: "Отправляйтесь в красочный сон с любимыми VTuber. Исследуйте их силу и собирайте идеальные отряды.",
    view_characters: "Посмотреть персонажей",
    view_guides: "Посмотреть руководства",
    view_all_articles: "Все статьи",
    no_active_team: "Нет активного отряда. Нажмите, чтобы собрать команду!",
    by_author: "Автор: {author}",
    read_time: "Время: {time}",
    leader_skill: "Навык лидера",
    passive_skill: "Пассивный навык",
    inactive_skills_title: "Неактивные требования навыков",
    no_unsatisfied_skills: "Все требования навыков выполнены. Ваш отряд работает отлично!",
    no_active_skills_msg: "Нет активных навыков для текущего отряда.",
    add_members_msg: "Добавьте участников в отряд для проверки пассивных навыков.",
    editing_label: "Редактирование:",
    primary_active_party: "Основной отряд",
    clear_slots: "Очистить слоты",
    my_character_roster: "Моя коллекция",
    select_all: "Выбрать все",
    deselect_all: "Снять выбор",
    roster_desc: "Имеется ({owned}/{total}). Автоподбор использует только отмеченных персонажей.",
    detailed_score_breakdowns: "Подробный анализ расчета очков",
    detailed_score_desc: "Математическая формула и соотношение аптайма для текущего состава",
    character: "Персонаж",
    final_stats_header: "Итоговые статы (S / T / P)",
    power: "Сила",
    active_buff: "Активный бафф",
    uptime: "Аптайм",
    special_buff: "Особый бафф",
    score_bonus: "Бонус очков",
    unit_score: "Очки персонажа",
    total: "ИТОГО",
    calculation_math: "Подробный расчет",
    final_stats_math: "1. Расчет итоговых статов",
    overall_power_math: "2. Расчет силы персонажа",
    active_uptime_math: "3. Расчет аптайма активного навыка",
    score_bonus_math: "4. Расчет бонуса очков",
    final_unit_score_math: "5. Расчет итоговых очков персонажа",
    applied_buffs: "Примененные баффы",
    triggers_in: "Срабатываний за",
    trigger_rate: "Шанс срабатывания",
    uptime_ratio: "Коэффициент аптайма",
    active: "Актив",
    special: "Особый",
    total_expected_bonus: "Ожидаемый суммарный бонус",
    active_contribution: "Вклад активного навыка",
    special_contribution: "Вклад спецподдержки",
    sar_contribution: "Вклад SAR",
    team_score_recon: "Сверка очков команды",
    outfit_leader: "Лидер аутфита",
    best_position: "Лучший слот",
    effective_magnitude: "Эффективная величина",
    condition_met: "Условие выполнено",
    condition_not_met: "Условие не выполнено",
    add_members_calc_msg: "Добавьте участников для просмотра расчетов"
  }
};

export function LanguageProvider({ children }) {
  const location = useLocation();
  const navigate = useNavigate();

  const [currentLang, setLangState] = useState(() => {
    const pathParts = window.location.pathname.split('/').filter(Boolean);
    const potentialLang = pathParts[pathParts.length - 1];
    const supportedLangs = LANGUAGES.map(l => l.code);
    if (supportedLangs.includes(potentialLang)) {
      return potentialLang;
    }
    return localStorage.getItem('theme_language') || 'en';
  });

  useEffect(() => {
    const pathParts = location.pathname.split('/').filter(Boolean);
    const potentialLang = pathParts[pathParts.length - 1];
    const supportedLangs = LANGUAGES.map(l => l.code);
    if (supportedLangs.includes(potentialLang)) {
      if (potentialLang !== currentLang) {
        setLangState(potentialLang);
        localStorage.setItem('theme_language', potentialLang);
      }
    }
  }, [location.pathname, currentLang]);

  const setLang = (code) => {
    const supportedLangs = LANGUAGES.map(l => l.code);
    if (supportedLangs.includes(code)) {
      setLangState(code);
      localStorage.setItem('theme_language', code);

      const pathParts = location.pathname.split('/').filter(Boolean);
      const lastPart = pathParts[pathParts.length - 1];
      let newPath = '';

      if (supportedLangs.includes(lastPart)) {
        newPath = '/' + [...pathParts.slice(0, -1), code].join('/');
      } else {
        newPath = '/' + [...pathParts, code].join('/');
      }
      
      navigate(newPath + location.search + location.hash);
    }
  };

  const t = (key, params = {}) => {
    const langDict = TRANSLATIONS[currentLang] || TRANSLATIONS['en'];
    let text = langDict[key] || TRANSLATIONS['en'][key] || key;
    
    Object.keys(params).forEach(p => {
      text = text.replace(`{${p}}`, params[p]);
    });
    return text;
  };

  return (
    <LanguageContext.Provider value={{ currentLang, setLang, t, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
